### ISSUE TITLE
libpqxx internal error in START_REPLICATION command

### ISSUE THREAD

**Issue by alfiyashka** [jtv/libpqxx#631] opened 2023-01-23 20:49 UTC
I got following error : libpqxx internal error: pqxx::result: Unrecognized response code 8, when I try to call command "START_REPLICATION"... Postgresql requires to perform this command without transaction.
My code:
                       char		cmd[256];
			XLogRecPtr startpoint;
			startpoint.xlogid = 0;
			startpoint.xrecoff = 0x16F49A0;

			snprintf(cmd, sizeof(cmd),
				"START_REPLICATION %X/%X TIMELINE 1",
				(unsigned int)(startpoint.xlogid), (unsigned int)startpoint.xrecoff);
			pqxx::nontransaction workNoncon(connectionObject);
			
			pqxx::result response1 = workNoncon.exec(cmd);
Can you look this please? What does the error code 8  mean?
Thank you.
Postgreql has 15 version, libpqxx has latest

**Comment by tt4g** [comment] 2023-01-24 06:49
The return value of `exec()` is `pqxx::resut`.
It is probably `pqxx::result::status_error()` that `throw` from the error message (`pqxx::connection::make_result()` is calling `pqxx::result::check_status()`) .

https://github.com/jtv/libpqxx/blob/7bf04aed8ca65c048bc197f3a97affad19bd0f26/src/connection.cxx#L713-L719

https://github.com/jtv/libpqxx/blob/7bf04aed8ca65c048bc197f3a97affad19bd0f26/src/connection.cxx#L207-L233

https://github.com/jtv/libpqxx/blob/4adfe1c99019766098415e7823c797c941d64368/src/result.cxx#L295-L335

The response code is gotten by the `PQresultStatus()` function, where `8` is `PGRES_COPY_BOTH`.
The official documentation (https://www.postgresql.org/docs/15/libpq-exec.html) says that `PGRES_COPY_BOTH` is a code that represents the start of replication.

> PGRES_COPY_BOTH
> Copy In/Out (to and from server) data transfer started. This feature is currently used only for streaming replication, so this status should not occur in ordinary applications.
 
However, `START_REPLICATION ...` does not return rows, even though pqxx must return rows in the return value of exec()`.

Looking at the API, it does not appear that it is possible to call maintenance commands from libpqxx that do not return rows, such as `START_REPLICATION`.

**Comment by alfiyashka** [comment] 2023-01-24 08:33
Thank you. You should add to handle this PGRES_COPY_BOTH code in libpxx. Overwise I had to work with libpx library for C. Please look this code: 
https://github.com/dvanaken/peloton-bwtree/blob/52785fb88239f1789b8b5502d645fbd64ebdfaac/src/postgres/backend/replication/libpqwalreceiver/libpqwalreceiver.cpp  and this https://github.com/chengyhol/pg/blob/a9cb728929480575100a40efa4a56edf581eee78/src/bin/pg_basebackup/receivelog.c
Here "START_REPLICATION..." is called on cycle. They check following: 
		if (PQresultStatus(res) != PGRES_COPY_BOTH)
		{
			pg_log_error("could not send replication command \"%s\": %s",
						 "START_REPLICATION", PQresultErrorMessage(res));
			PQclear(res);
			return false;
		}

**Comment by jtv** [comment] 2023-01-24 08:37
Yes, it should be a simple matter of adding a case to handle this status code.  I just wasn't aware that this status code had been added.  There are some other new codes as well, so we'll want to support them too.

("New" is relative of course.  I started libpqxx in the late 20th century.  This particular switch has not needed a lot of updating since then.)

I should have a fix ready for testing later today.

**Comment by alfiyashka** [comment] 2023-01-24 08:41
thank you

**Comment by jtv** [comment] 2023-01-24 12:18
@alfiyashka could you see whether the code change in #632 gets you to a working state?  (The branch is called `new-response-statuses`.)

**Comment by jtv** [comment] 2023-01-25 16:07
@alfiyashka if it works, I can also backport the change to the latest release, so you can start using it without having to rely on the development version.

First I'll need to know whether it works though.  :-)

**Comment by jtv** [comment] 2023-01-25 23:11
By the way @tt4g I can't think what gave you the impression that libpqxx wouldn't work for maintenance statements that don't return any rows.  Such statements should work just fine, by design.  The only problem was the introduction of a different status code for this one particular command.  That status code wasn't supported yet, in libpqxx but that looks like a simple matter of adding a case to a switch.

**Comment by tt4g** [comment] 2023-01-25 23:22
Since there was no `case PGRES_COPY_BOTH` branch for the return code of `PQresultStatus()`, I assumed that the library does not support cases that do not return results as in this problem.

**Comment by jtv** [comment] 2023-01-26 00:16
> Since there was no `case PGRES_COPY_BOTH` branch for the return code of `PQresultStatus()`, I assumed that the library does not support cases that do not return results as in this problem.

That's `PGRES_COMMAND_OK`.  :-)

**Comment by alfiyashka** [comment] 2023-01-26 07:21
thank you!

**Comment by jtv** [comment] 2023-01-26 09:27
> thank you!

Does that mean it worked?  (Sorry for being insistent here, I'd like to get it clear before I commit the change.)

**Comment by jtv** [comment] 2023-02-17 18:34
@alfiyashka can you confirm that it worked?  If so, I can merge the change into the mainline code.

**Comment by jtv** [comment] 2023-02-26 21:05
Well, I've merged the change.  Absent any further feedback, all I can do is close the ticket.

**Closed by jtv** 2023-02-26 21:05 UTC
