### ISSUE TITLE
Install libpqxx in VS code

### ISSUE THREAD

**Issue by HLneoh** [jtv/libpqxx#281] opened 2020-02-23 07:42 UTC
How to include libpqxx in visual studio code?

**Comment by tt4g** [comment] 2020-02-23 11:08
Unfortunately, there is no standard way for development C/C++.
[C/C\+\+ \- Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) will auto detect installed libpqxx in your machine.

This link is helpful for C / C ++ development using Visual Studio Code: [C\+\+ programming with Visual Studio Code](https://code.visualstudio.com/docs/languages/cpp)

Although not mentioned in the link, there is also a way to use a package manager such as meson or conan.

**Comment by HLneoh** [comment] 2020-02-23 11:38
Hi, the compiler and build tools that I am using are Windows MSVC. How to use conan to install libpqxx in my machine?

**Comment by tt4g** [comment] 2020-02-23 12:07
One of my project uses CMake and https://github.com/conan-io/cmake-conan.

Example of using project libraries with conan in CMake project:

`conanfile.txt`:

```
[requires]
libpq/9.6.9@bincrafters/stable
libpqxx/7.0.1@bincrafters/stable

[generators]
cmake

[options]
libpq:shared=True
libpq:with_zlib=False
libpq:with_openssl=False
libpqxx:shared=True

[imports]
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my local "bin" folder
lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my local "bin" folder
```

`CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.12.0)
project(foo VERSION 0.1.0 LANGUAGES CXX)

##############################################################
# https://github.com/conan-io/cmake-conan

# Download automatically, you can also just copy the conan.cmake file
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake"
                 "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(BASIC_SETUP CMAKE_TARGETS
                BUILD outdated
                SETTINGS compiler.cppstd=${CMAKE_CXX_STANDARD}
                PROFILE_AUTO ALL)

##############################################################

add_executable(foo ${YOUR_SOURCE_FILES})
target_link_libraries(foo CONAN_PKG::libpqxx)

```

**Comment by jtv** [comment] 2020-02-23 18:24
Thanks once again for stepping in @tt4g — Windows/MSVC is probably the part I know the least about.  Followed by CMake.  :-)

**Comment by HLneoh** [comment] 2020-02-24 05:26
@tt4g  What header and namespace should I include in order for me to use libpqxx function?

**Comment by tt4g** [comment] 2020-02-24 08:17
@HLneoh `#include <pqxx/pqxx>` and see official documentation: [libpqxx: Getting started](https://libpqxx.readthedocs.io/en/7.0.2/a01329.html)

**Comment by HLneoh** [comment] 2020-02-24 08:31
@tt4g What is the difference of using libpq-fe.h and pqxx/pqxx?  I am using libpq-fe.h instead of pqxx/pqxx. It is because runtime library debug error is prompted when I am using pqxx/pqxx.

**Comment by tt4g** [comment] 2020-02-24 08:54
`libpq-fe.h` is header file of libpq. this is C language API.
`pqxx/pqxx` is header file of this repository library. this is C++ language API.

Both libraries can connect to a PostgreSQL database.
However, libpqxx is easier to use.

**Comment by jtv** [comment] 2020-02-24 11:55
@HLneoh what error do you get when using pqxx/pqxx?

**Comment by HLneoh** [comment] 2020-02-24 14:39
@jtv 
![image](https://user-images.githubusercontent.com/25906607/75161301-8649aa00-5756-11ea-9f66-bd6f48329e07.png)

**Comment by tt4g** [comment] 2020-02-24 21:49
@HLneoh Can the code executed just before `abort()` be examined by debugging?

**Comment by jtv** [comment] 2020-02-25 09:25
Is there any console output?

Also, there are some "usual sources of problems" that may be worth checking:
 * Make sure you don't mix "Release" binaries with "Debug" binaries.  For example, a Debug build of libpqxx won't be able to work with a Release build of libpq, and so on.
 * Does your code catch exceptions and report them properly?
 * Do you have enough disk space?  (Just mentioning it because one piece of advice on the internet says it might be the cause of an error like this.)

Another thing that usually helps is to reduce your code to the _absolute minimum that reproduces the error._  It makes debugging a lot easier, and often it's enough to reveal the problem immediately.

**Comment by jtv** [comment] 2020-03-25 14:31
@HLneoh any news on this?

**Comment by jtv** [comment] 2020-03-31 15:33
If there's no further news, I'll just close this one.  Feel free to open a new issue if more details come up.

**Closed by jtv** 2020-03-31 15:33 UTC
