### ISSUE TITLE
Map result into structures

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#271] opened 2020-02-01 21:00 UTC
Hi!

Thank you for the great library and 7.0 release!
Since you switched to cpp17, probably it will be helpful to have following feature - map result into some data structure.

Presentation in Russian (see page 14 and maybe others too):
https://assets.ctfassets.net/oxjq45e8ilak/4YubsfskRBgTNq4s6Wx6h7/6adf149eb7094db068228d5dd91f5ca0/Sergey_Fedorov_Shablony_C_i_bazy_dannykh.pdf

```
struct FooBar { int foo; std::string bar; }; // RFC 3092
auto trx = cluster.Begin();
auto res = trx.Execute("select foo, bar from foobar where foo = $1", 42);
auto foobars = res.AsContainer<std::vector<FooBar>>();
trx.Commit(); 
```

In terms of pqxx this will be something like
```
pqxx::work txn(conn);
auto rows = txn.exec("...");
row[0].as<FooBar>();
rows.as<std::vector<FooBar>>();
```

---

This is just friendly feature request.
Probably you have some own vision on similar feature.

**Comment by jtv** [comment] 2020-02-01 21:38
Thank you for your kind words.

Actually, this came up a long, long time ago with a library called...  I think it was _libpqxxobject._  But C++ wasn't quite ready for it then, and perhaps it is now.  Certainly `stream_from` and `stream_to` are a lot closer to this already.

So I'd like to keep it in mind.  For now I need to focus on polishing the early 7.0 releases, and surviving FOSDEM.  :-)

**Comment by jtv** [comment] 2020-02-09 11:37
I'm working that goes in the right direction.  ;)

**Comment by omerbn** [comment] 2020-02-09 17:15
I want to join @egorpugin 's words - this is a great library :)
I'd also want to to ask when are you going to support user-defined structures in `stream_from` and `stream_to`?

I aim to use your library to load 150M rows from DB ASAP.
On a small data-set (4.5M rows) in a non-`stream_from` way, it takes ~9s.
I'd like that to load all 150M rows in that time. Do you think is a feasible goal?

Thanks :)

**Comment by jtv** [comment] 2020-02-09 18:59
@omerbn thank you too.  :-)

*The bad news:* I don't see a way to map straight to user-defined structs and classes in C++17.  We can have a fresh look once we're on C++20.

*The good news:* turns out there's some pretty good substitutes.  The patch I've been working on today would let you write things like:

    void print_tags(transaction_base &tx)
    {
        for (auto [id, name] : tx.stream("SELECT id, name FROM tag ORDER BY name"))
            std::cout << id << " - " << name << '\n';
    }

As you can see, you're not getting a class or struct, but you _can_ get a `std::tuple` and the language knows how to map that into variables.  Pretty neat, right?

I haven't actually tested performance yet, but I believe it could end up being faster as well, if the results aren't very small.

If you'd like to play with this upcoming change, have a look at #274.  Let me know what you think while I can still make changes!

**Comment by jtv** [comment] 2020-02-09 19:01
By the way, I can tell from my typing mistakes today that I'm not quite well.  So view that patch with extreme suspicion, and please _please_ let me know about anything I got wrong.  :-)

**Comment by omerbn** [comment] 2020-02-09 19:37
@jtv Sure. Thanks.
Feel well :)

**Comment by omerbn** [comment] 2020-02-09 19:40
@jtv BTW - I'm ok with using a `std::tuple` to map the variables. The problem is that I have a field in DB that is an array of user-defined type:

```
CREATE TYPE info AS (
   "flong" bigint[],   
   "fshort" smallint[]
);

CREATE TABLE "rels" (
   "_id" BIGSERIAL,
   "type"   smallint NOT NULL,
   "meta"   smallint NOT NULL, 
   "info"   info[] DEFAULT NULL
);
```

How can I use `tuples` in order to parse it while using `stream_from`?
Thanks

**Comment by egorpugin** [comment] 2020-02-09 20:54
@jtv 

> The bad news: I don't see a way to map straight to user-defined structs and classes in C++17. We can have a fresh look once we're on C++20.

I think there are some explanations in the presentation from the first post about the implementation.
Also I suspect it is EXACTLY related to mapping results into tuples and then into structures.
(But I did not dive into that c++17 magic myself, just thoughts.)

**Comment by jtv** [comment] 2020-02-10 09:39
Unfortunately I don't know Russian (call me _nekulturnyi_ if you want) so I didn't expect to be able to understand the presentation.  :)

**Comment by jtv** [comment] 2020-02-10 10:05
@omerbn for your arrays I would suggest a combination of steps:
 * I think I can define a super-efficient "conversion" of a field to `std::string_view`.
 * You can define your own conversion for your custom type.
 * With those two things, you can use the `array_parser` to parse the array.

Of course you can also just continue to use `pqxx::result` and do it the old-fashioned way.

**Comment by omerbn** [comment] 2020-02-10 10:09
@jtv right now I'm using the old-fashioned way ```pqxx::result``` and it works great! 
BUT just not as-fast-as using `stream_from`. 
I'm looking for a way to 'teach' `stream_from` to parse my user-defined data.

Any ideas?

**Comment by omerbn** [comment] 2020-02-10 10:09
@jtv do I need to add some structs to conversions.hxx and re-compile? if so, what exactly?

**Comment by jtv** [comment] 2020-02-10 10:33
You don't need to add anything to conversions.hxx, but you do need to specialise a few templates in the `pqxx` namespace.  Just this last week I added some documentation for supporting custom type conversions in `include/pqxx/docs`.

**Comment by omerbn** [comment] 2020-02-10 10:38
I'll take a look

**Comment by omerbn** [comment] 2020-02-12 16:56
Thanks, I managed :)

**Comment by jtv** [comment] 2020-02-16 18:10
@omerbn the latest updates to my "streaming queries" branch lets you "convert" fields to `std::string_view`.  (I reworked everything, which wasn't easy but eliminated a lot of waste too).

Of course you'll need to be careful with lifetimes when you use `string_view`.  The string stays alive for the duration of a single iteration of the loop.  On the next iteration it's either overwritten or deallocated.

But with that branch, you should now be able to read your array field into a `std::string_view`, and then feed that value into a `pqxx::array_parser`.

**Comment by jtv** [comment] 2020-02-16 22:19
Ooo, this looks good.  I just ran a brainless little _totally non-representative_ stupid quick-and-dirty benchmark, querying a million and a half rows at  a time.  Each row contained an integer, a short sting, and a floating-point number.  I converted the values and printed them to /dev/null.

The new streaming API was about 15% faster than retrieving and iterating a `result` object.  And you start getting data sooner too, because you don't need to wait for the full result to come in before you can start processing.  Totally non-representative, but still, nice to see.  I believe the streaming interface would probably be _slower_ on small query results, but it seems to scale better..

**Comment by jtv** [comment] 2020-02-16 22:56
@egorpugin I _finally_ took the time to look at that Russian presentation...  Luckily the Russian word for "template" is pretty close to the Dutch — _sjabloon._  So I could actually decypher bits and pieces.  :-)

Is this presentation about a Yandex postgres driver?  In many parts the design looks a lot like my own, though probably designed for C++14 or C++17 from the start.

Page 51 revealed the trick for mapping a `struct`: it's something Boost's pfr library can do, apparently.  So the trick is simply "use Boost."  :)  There are some restrictions of course, e.g. the `struct` must be a POD, and there's a mention of a "loophole" that must be available: http://apolukhin.github.io/magic_get/boost_precise_and_flat_reflectio/requirements_and_limitations.html

**Comment by egorpugin** [comment] 2020-02-16 23:00
> Is this presentation about a Yandex postgres driver?

Yes. They write a lot of stuff optimized for their need from scratch.

>  it's something Boost's pfr library can do, apparently. So the trick is simply "use Boost."

Seems like this. But for now pfr is not in boost and I did not check if it require any deps from there.
Current repo is at https://github.com/apolukhin/magic_get

**Comment by jtv** [comment] 2020-02-17 08:53
I don't think I should mess with these things in libpqxx though, until we get Reflection in C++20.  :)

But if the new "query streaming" API works out, perhaps it won't matter.  We can now just do the `for (auto [a, b, c] : query)` trick.

Now I'm sitting here wondering to what extent their design was influenced by libpqxx...  Last time I found a library this similar to libpqxx, my name was mentioned in the docs.

**Comment by egorpugin** [comment] 2020-02-17 09:20
> I don't think I should mess with these things in libpqxx though, until we get Reflection in C++20. :)

What feature do you mean?
C++20 is complete, but there's no much reflection AFAIK.

**Comment by jtv** [comment] 2020-02-17 09:32
Oh!  We're getting so many new features in C++20, perhaps I just _assumed_
that we were getting reflection.  Can't wait either way.  :)

Do you think you could play a bit with my "streaming queries" branch, and
see if there's any weaknesses?  If it works out, I may just call this
libpqxx 7.1.

**Comment by egorpugin** [comment] 2020-02-17 09:44
I use preprared statements everywhere in my project. (Had tough times updating those calls for 7.0. :) )
Does stream_from work with prepared statements?

Also from this commit https://github.com/jtv/libpqxx/commit/7662d181ac5890933146818709352e5722d36c16 I think whether it's possible to improve API.
Maybe to use `operator()()` instead of `iter()`? Maybe add separate class for it?

I'll try to test current implementation today with some hello world project and respond here.

**Comment by jtv** [comment] 2020-02-17 12:42
Perhaps you could execute prepared statements just by doing an `EXECUTE` query...  But you'd still have to convert the parameters to text yourself (using `to_string()` or `quote()`) so probably not too convenient.

As for the `iter()`, I don't recall just now why I couldn't just iterate the stream directly.  That would have been my first choice.  But why bother with `stream_from::iter()` when you can use `transaction_base::stream()`?

**Comment by egorpugin** [comment] 2020-02-17 13:28
> As for the iter(), I don't recall just now why I couldn't just iterate the stream directly.

True.
`for (auto [...] : stream)` is nice and clean.

> But why bother with ...

I'm not familiar with those APIs.
Let me try it first. :)

**Comment by egorpugin** [comment] 2020-02-19 21:27
Ok, tried stream_from. It's not very suitable for my needs.
Also poked with boost::pfr converting rows into structures.
Did this in very dumb way. See https://gist.github.com/egorpugin/598176b1b31f95df0b22847cf10c7336#file-main-cpp-L32-L56

Maybe it's possible to write some wrappers or macros for smooth data retrieval. Maybe I'll dive into that template magic.

**Comment by jtv** [comment] 2020-02-19 22:20
Looks like the problem is still the ability to execute prepared queries then.  One thing we can still consider is to support the same trick I did for `stream_from`, but for the `exec*` functions:

    for (auto [id, name, value] : tx.exec_prepared("my_query").iter<int, std::string_view, std::string>())
    {
        // ...
    }

The `iter()` at the end is ugly, but necessary I think.  Otherwise we'd have to have templated versions of just about every `exec*()` function.

**Comment by egorpugin** [comment] 2020-02-19 23:37
In this case iter looks like `.AsContainer()` from first post, so it's ok.
We show explicitly that we need result in some wrapped form.

I think it's also good to not rush this feature, so better design and naming will come with time.
As for playground, maybe it's ok to make a branch or write a warning near such experimental methods (guard with PQXX_EXPERIMENTAL), so people will know that APIs are subject to change.

**Comment by jtv** [comment] 2020-02-20 09:02
Yes, that might be a good idea.  I really don't like having to manage multiple branches at the same time.  Leads to mistakes, holds back improvements.

**Comment by egorpugin** [comment] 2020-02-20 16:41
Ok, I've implemented helper class and it seems it is very suitable for me.
See three example loops there and the wrapper above:
https://gist.github.com/egorpugin/eced222ace1c2782d869c6e713397d91#file-main-cpp-L99

**Comment by jtv** [comment] 2020-02-22 09:20
As a sidenote, did you know that your `assign()` can be done without the "template recursion" to go through the elements on the tuple?  You can do it iteratively using folding expressions like in `stream_from.hxx`, function `do_extract`.

**Comment by egorpugin** [comment] 2020-02-22 11:22
I do not know template recursion good enough. Just googled function version somewhere on stackoverflow. :)

**Comment by jtv** [comment] 2020-03-31 15:38
I'm hoping to release 7.1.0 soon, which would include the new "streaming queries" feature.  It effectively does mapping rows of data into tuples.  That's not the complete feature that you were asking for, but it may be close enough.  If nobody minds, I'd like to close this ticket soon, and then if people still want further extensions to this area, feel free to file new issues.

**Closed** 2020-04-14 21:10 UTC
