### ISSUE TITLE
New `exec_prepared` and `exec_params` don't support runtime variable argument lists

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#184] opened 2019-05-14 03:55 UTC
Unless I'm missing something, the old `prepared` followed by `exec` methods (as we use [here](https://github.com/KayEss/fost-postgres/blob/f451b9cef43bdf934d1996e80542b9fddf02720c/Cpp/fost-postgres/stored-procedure.cpp#L22) and [here](https://github.com/KayEss/fost-postgres/blob/f451b9cef43bdf934d1996e80542b9fddf02720c/Cpp/fost-postgres/stored-procedure.cpp#L30)) no longer support the case where we don't know how many parameters we need until runtime.

I'm looking at the APIs at these two locations:
* https://github.com/jtv/libpqxx/blob/master/include/pqxx/transaction_base.hxx#L284
* https://github.com/jtv/libpqxx/blob/master/include/pqxx/transaction_base.hxx#L347

What's the intended method for doing this now? I'm looking at current HEAD of master. (ah, found something, see below)

We've been used prepared statements for this, but actually for most of our use cases it'd probably be better to use `exec_params` method.

What I think I really need is something with a function signature like this:

```cpp
template<typename Iter, typename Func>
result exec_params(std::string_view query, Iter begin, Iter end, Func transform);

template<typename Iter, typename Func>
result exec_prepared(std::string_view query, Iter begin, Iter end, Func transform);
```
Hopefully it's possible to do something with `string_view` rather than `c_str` for the return type from the transform, but for that to work I believe you'll actually need to expect `transform` to return `std::optional<std::string_view>`.

I've just found #75 which also talks about this, so I'll have a go at that solution. The only way I found out about `dynamic_params` was to look at the commit referenced in the issue :-) Without the transform function it's going to cost several allocations to do the data transform I need :(

**Comment by jtv** [comment] 2019-05-14 07:43
Clearly `dynamic_params` needs documenting in the Markdown docs.  Also, I should lift the type out of the `pqxx::internal` namespace so that it'll slot into the generated documentation.  The old parameter-passing mechanics necessarily exposed types that I considered implementation details, and I may have overreacted by marking them as "internal."

**Comment by KayEss** [comment] 2019-05-14 08:01
You can see our new code that we've needed to do. As you can see the API forces us to allocate two copies of the arguments vector because we can't stream the data.

https://github.com/KayEss/fost-postgres/blob/develop/Cpp/fost-postgres/stored-procedure.cpp

It might be enough to support a transform lambda on the `dynamic_params` data structure, but I think you also need to consider the ranges proposal, and instead take a range (then the transform can be wrapped into the range). The transform can also be wrapped up into a coroutine, but again, you need to take a range instead of begin and end iterators.

I believe that we really need a better API design here still :-) Sorry :-(

**Comment by jtv** [comment] 2019-05-18 14:48
@KayEss  I suppose you _could_ wrap the accessor into a custom iterator wrapper, but that sounds like a royal pain.

There's not a lot I can do about streaming your parameters without breaking open the libpq abstraction, but an accessor sounds doable.  Even for the case where the argument is a container, thanks to SFINAE.  Hang in there, I'll go try.

**Comment by KayEss** [comment] 2019-05-18 14:53
Yeah, having to do a custom iterator for this (without coroutines TS) *is* a royal pain :-)

All I need is that transform functor!

**Comment by jtv** [comment] 2019-05-18 15:49
Rabbit holes.  Blinked and discovered that I was writing a completely generic "accessor wrapper" for any iterator type.  Which doesn't look all that hard.  Now I'm wondering...  Would a thing like that be useful at all?  Might it already be in the standard library somewhere?

**Comment by KayEss** [comment] 2019-05-18 15:54
Maybe you're thinking of ranges in C++20?

**Comment by jtv** [comment] 2019-05-18 15:57
I salivate at the thought of C++20 but yes, I suppose it's a slightly different way of doing the same thing.

**Comment by KayEss** [comment] 2019-05-18 15:58
Just be careful you don't hurt your keyboard. Those things can be expensive

**Comment by jtv** [comment] 2019-05-18 16:00
Not mine.  I'll see about the simple approach: replace `*it` with `accessor(*it)`.

**Comment by jtv** [comment] 2019-05-18 17:44
Gah.  The mechanics of _storing_ a generic-callable-of-whatever-kind-and-type is doing my head in!  It feels at least one level of complexity beyond what `std::transform()` does, where it's just a templated argument and there's no need to go into its type in any detail.

**Comment by KayEss** [comment] 2019-05-18 17:49
It's just the type of the parameter to your `make_xxx` function, and you can template on that just as easily as you can on the other types. Because it may include a closure you'll need to move it, but at the end of the day, it's just another class or function pointer.

I can probably work up an example tomorrow if you're still stuck, but something tells me you won't be :-)

**Comment by jtv** [comment] 2019-05-18 19:50
@KayEss I've got something working now.  Could you try it?

I'm thinking I'll lift `dynamic_params` itself out of `pqxx::internal` so you can construct it directly.  At that point you can just construct the thing yourself, and `make_dynamic_params` will be just a convenience function to help with the template argument deduction tor the constructors that take a container.  That's why I didn't add an accessor version for the pair-of-iterators version, but obviously I could add one.

**Comment by jtv** [comment] 2019-05-18 21:17
There is now also a bit of documentation in `include/pqxx/doc/prepared-statement.md`.

**Comment by JadeMatrix** [comment] 2019-05-19 04:22
Just my 2¢, I ran into a similar problem recently — needing a single concrete type to act as an interface to do something with any other type.  I ended up with something like this (original code was doing something completely different & much more complex):

```cpp
class Mapper
{
protected:
    std::function< void( std::ostream& ) > _accessor;
    
public:
    template< typename T > Mapper( T&& v ) :
        _accessor{ [ v ]( std::ostream& out ){ out << v; } }
    {}
    
    void apply( std::ostream& out ) const { _accessor( out ); out << "\n"; }
};
```

So probably similar to what @KayEss was talking about.  Hope this might be helpful.  Note you can set this up to additionally capture non-`const` references to the arguments, but that requires a bit more template magic due to deduction rules preferring `T&&`.

**Comment by KayEss** [comment] 2019-05-19 06:56
That's getting there. It doesn't quite work unfortunately :-)

If I have to return a C string then I really need the container to be mutable because it still has to own the memory returned after the accessor function runs. The alternative is to return something like a `std::optional<std::string_view>`, but then I get an error like this:

```
../../libpqxx/include/pqxx/internal/type_utils.hxx:160:24: error: implicit instantiation of undefined template 'pqxx::string_traits<std::basic_string_view<char, std::char_traits<char> >, void>'
    { return (not v || string_traits<I>::is_null(*v)); }
```

When you pass a string down to libpq does it need to be a C string, or can you pass a pointer and length?

**Comment by jtv** [comment] 2019-05-20 08:28
Yes actually I'm hoping to move the whole string-conversion machinery over to `string_view`, and until then, converting a `string_view` to a string is a weird thing that I don't want to make too attractive.

Separately from that, I'd like to bypass the intermediate storage inside a `string` for the special case where you pass C strings or `string_view`.  As you surmise, libpq just wants a C string, and libpqxx just wants to avoid having that storage destroyed while it's still needed.

**Comment by KayEss** [comment] 2019-05-20 08:49
I kind of thought as much, and of course the problem with you supporting `string_view` is that you can't get a C string from it, you'd need to allocate. This is actually why I need the container to be mutable -- so those allocations can happen.

Until/unless libpq changes it seems like there may not be much point in your supporting `string_view` in most places.

**Comment by jtv** [comment] 2019-05-20 09:11
Ah yes, of course you passing a `string_view` won't help me if there's no terminating zero.  You'll also have noticed the annoying mishmash of `std::string`, `const char *`, and `std::string_view`, depending on what libpq wants.  Maybe it's time to start looking into custom replacements of individual libpq functions...

**Comment by jtv** [comment] 2019-05-25 13:50
I'm actually getting a fair number of `string_view` in...  I just replaced the `const char[]` first parameter to `from_string` with a `string_view`, and scrapped the versions which took the length as a third argument.

Now considering doing something similar for `to_string`.  But it changes the lifetime aspect of the contracts, so probably best to do it as an additional function.

**Comment by jtv** [comment] 2019-05-25 17:34
Actually, lifetimes aren't an obstacle, but there are other problems: performance, and the sheer drudgery of inlining.

To summarise the scheme I had in mind:
 * `to_string` (or a new function) takes an additional argument: a callback.
 * The callback takes a `string_view`.
 * The default value for the callback returns a `string` constructed from the `string_view`.
 * `to_string` (or the new function) builds up its result, passes it to the callback, and returns whatever the callback returns.

In simple cases, you could pass a lambda which consumes the output string and processes it, so you no longer need the string after the lambda finishes.  The lambda could return `void`.

Advantages:
 * `string_view` is nicely lightweight.
 * `to_string` implementations get a lot of freedom in how they build up the string, e.g. in a buffer on the stack, or a string literal.
 * Minimises intermediate string copying when use of the result string is limited.

Disadvantages:
 * Callbacks are awkward.
 * If the `to_string` implementation happens to construct its result inside a `std::string`, it loses the opportunity for move semantics.
 * A lot of code needs to go inline so that the callback can be templatised.

I'm starting to wish that a `std::string_view` could own reference-counted storage, and take over a `std::string`'s storage through move semantics.  If we had that, different implementations of `to_string` could optimally return a string constant, or a working buffer, as appropriate.  @KayEss, didn't you build something like this at one point?

**Comment by jtv** [comment] 2019-05-25 18:25
Oh!  What a fool I've been.  There's another option for "inverting the call chain" and handing back a `string_view` when appropriate.  Instead of extending `to_string`, I could define _a type_ for converting a type to a string.  Constructor takes your input object, and produces something with an `operator std::string_view()`, an `operator const char *()`, and what have you.  Maybe even a "destructive get" which moves a `std::string` into the caller's hands.

Still not ideal, since it leaves the optimisation choice between `string` and `string_view` in the caller's hands.  If performance is a huge issue, maybe the type should have some metadata which lets you template your way out of it: "which would you _rather_ give me?"

**Comment by KayEss** [comment] 2019-05-26 13:02
> I'm starting to wish that a `std::string_view` could own reference-counted storage, and take over a `std::string`'s storage through move semantics. If we had that, different implementations of `to_string` could optimally return a string constant, or a working buffer, as appropriate. @KayEss, didn't you build something like this at one point?

Actually, that's pretty much exactly what the string type we're interfacing to your code does. You might be interested in reading this page: https://github.com/KayEss/f5-cord/blob/master/DESIGN.md

The main point is that getting a C (zero terminated) string  from one of these must be mutating. I think in our APIs I need to overload for both const and non-const containers.

**Comment by jtv** [comment] 2019-06-01 23:41
Meanwhile, I've fixed a critical bug in `dynamic_params` where some of the accessor-less constructors neglected to initialise the accessor function to an identity function.  @KayEss, does `dynamic_params` suit your needs in its present form?  Apart from the need to zero-terminate the strings we pass to libpq, that is?

If so, we can close this issue.

**Comment by KayEss** [comment] 2019-06-02 06:02
Did you add an overload for mutable containers and a mutating accessor function?

**Comment by KayEss** [comment] 2019-06-02 10:09
Just to make this a bit more clear. I would like to be able to implement a diff that looks like this:

```diff
 namespace {
-    template<typename Iter, typename Func>
+    template<typename Coll, typename Func>
     auto exec_prepared(
             pqxx::transaction<pqxx::serializable> &trans,
             std::string const &name,
-            Iter begin,
-            Iter end,
+            Coll &collection,
             Func transform) {
-        std::vector<char const *> dynargs;
-        std::transform(begin, end, std::back_inserter(dynargs), transform);
         return trans.exec_prepared(
                 name,
                 pqxx::prepare::make_dynamic_params(
-                        dynargs.begin(), dynargs.end()));
+                        collection, transform));
     }
 }
 ```

This saves the new vector that I currently need to allocate.

**Comment by jtv** [comment] 2019-06-02 13:18
In that case, can't I just remove the `const` from the container reference parameter to the constructor which also takes the accessor?

**Comment by jtv** [comment] 2019-06-02 13:59
Actually, that won't help, since it's you modifying your container,  through a reference of your own — not me modifying the container through the reference you pass me.  So I still don't have a clear picture of what the problem is, and what would currently stop you from making the change you want.

And bear in mind, you don't _have_ to pass me your arguments in `const char *` form if it's not convenient.  I'm in the process of re-doing the whole string conversion framework, and there may be room for tricks like storing all the parameter strings in a single big buffer, so each parameter costs you a copy operation but not an allocation.

**Comment by KayEss** [comment] 2019-06-02 17:36
> n that case, can't I just remove the `const` from the container reference parameter to the constructor which also takes the accessor?

Yeah, I think that's actually all that's required. 

If you can take a `string_view` efficiently then that's great, but if if it costs an allocation per argument it's not so interesting.

**Comment by KayEss** [comment] 2019-06-02 17:37
Actually, I'm not sure I understand what the problem with the old API was. Why did you want to change it?

**Comment by jtv** [comment] 2019-06-02 17:48
The old string conversion API?  It dealt in `std::string` — lots of allocations!

**Comment by KayEss** [comment] 2019-06-03 02:32
No, I meant the old API for setting arguments on a prepared statement.

**Comment by jtv** [comment] 2019-06-03 07:10
The old prepared/parameterised statement APIs had some rigmarole that can now be done with parameter packs.  And as you've seen, it afforded an unexpected (to me) place where users could splice in and trip over lifetime issues and get hurt by code changes.

**Comment by jtv** [comment] 2019-06-17 16:30
@KayEss I've prototyped a new class template, `str`, for representing values as `std::string_view` and avoiding buffer allocation.  Actually it starts with a kind of generalised version of `to_chars` which returns a `std::string_view` — which may or may not point to text inside the buffer you give it.  Will try to get it into `master` soon, so you can have a look.

**Comment by jtv** [comment] 2019-08-28 21:02
@KayEss  can we close this bug now?

**Comment by KayEss** [comment] 2019-08-29 04:48
I'm still using the work around. Hopefully I'll have time to try it out over the weekend. Can we wait that long? :-)

**Comment by jtv** [comment] 2019-08-29 12:53
Yes, yes, I think we can just about manage that.

**Comment by KayEss** [comment] 2019-09-01 03:59
I suppose there may be some other way I'm now supposed to do this. Should I look into using a `std::string_view` now?

To support a mutating accessor I think these two changes are needed (basically just handle the non-const collection).

```diff
diff --git a/include/pqxx/internal/statement_parameters.hxx b/include/pqxx/internal/statement_parameters.hxx
index 6dfec575..4b7804ba 100644
--- a/include/pqxx/internal/statement_parameters.hxx
+++ b/include/pqxx/internal/statement_parameters.hxx
@@ -86,6 +86,13 @@ public:
                std::end(container),
                acc)
   {}
+  template<typename C> explicit
+  dynamic_params(C &container, ACCESSOR &acc) :
+       dynamic_params(
+               std::begin(container),
+               std::end(container),
+               acc)
+  {}
 
   IT begin() const { return m_begin; }
   IT end() const { return m_end; }
diff --git a/include/pqxx/prepared_statement.hxx b/include/pqxx/prepared_statement.hxx
index 2edcb5d9..0fa2c2d5 100644
--- a/include/pqxx/prepared_statement.hxx
+++ b/include/pqxx/prepared_statement.hxx
@@ -96,6 +96,18 @@ make_dynamic_params(
   using IT = typename C::const_iterator;
   return pqxx::internal::dynamic_params<IT, ACCESSOR>{container, accessor};
 }
+
+template<typename C, typename ACCESSOR>
+inline auto
+make_dynamic_params(
+       C &container,
+       ACCESSOR accessor)
+{
+  using IT = typename C::iterator;
+  return pqxx::internal::dynamic_params<IT, ACCESSOR>{container, accessor};
+}
+
+
 } // namespace pqxx::prepare
 
 #include "pqxx/compiler-internal-post.hxx"
```

I'll try altering my code to return `std::string_view` instead and see how that comes out.

**Comment by KayEss** [comment] 2019-09-01 04:11
I've tried three versions of the accessor lambda:

```cpp
[](fostlib::string const &arg) { return static_cast<std::string_view>(arg); }
```

Gives an error about missing type traits:

```
../../libpqxx/include/pqxx/strconv.hxx:261:17: error: implicit instantiation of undefined template 'pqxx::string_traits<std::basic_string_view<char, std::char_traits<char> >, void>'
  if constexpr (traits::has_null) return traits::is_null(value);
                ^
```

```cpp
[](fostlib::string const &arg) -> std::optional<std::string_view>
            { return static_cast<std::string_view>(arg); }
```
Also gives an error about missing type traits:

```
../../libpqxx/include/pqxx/strconv.hxx:261:17: error: implicit instantiation of undefined template 'pqxx::string_traits<std::basic_string_view<char, std::char_traits<char> >, void>'
  if constexpr (traits::has_null) return traits::is_null(value);
                ^
```

```cpp
[](fostlib::string &arg) { return arg.shrink_to_fit(); }
```

Gives an error *unless* I apply the above patch because the collection is always immutable at the moment.

```
../../libpqxx/include/pqxx/internal/statement_parameters.hxx:94:17: error: no matching function for call to object of type '(lambda at ../../fost-postgres/Cpp/fost-postgres/stored-procedure.cpp:40:13)'
    -> decltype(std::declval<ACCESSOR>()(value))
                ^~~~~~~~~~~~~~~~~~~~~~~~
```

When I apply the above patch then all of our code compiles and tests pass (I haven't run yours).

**Comment by jtv** [comment] 2019-09-01 12:53
I only just finally realised that what you want is to modify not your container, as I had thought from the outset for some reason, but _elements of_ your container, and therefore you need iterators which are not `const_iterator`s.  So I made the container non-`const`.  Hope that helps.

Then there's the problem with `string_traits`.  We can't have a full `pqxx::string_traits<std::string_view>`, because its  `from_string` wouldn't have anywhere to put the string contents.  Luckily `string_traits` has been evolving towards a "null traits" with the actual string conversions moving out of the struct.  So I have no qualms about defining a `string_traits` for `string_view` _without_ a `from_string`.

(By the way, I've also introduced a `pqxx::zview` which is a `std::string_view` but with the added guarantee of being zero-terminated.  Basically just a marker class.  I have yet to add a bunch of clever overloads for functions that pass C-style strings on to libpq.)

**Comment by KayEss** [comment] 2019-09-01 14:09
> I only just finally realised that what you want is to modify not your container, as I had thought from the outset for some reason, but _elements of_ your container,

Yeah, metonymy is a terrible thing and tough to avoid :-) Sorry about that

Just looking at your latest diff, I'm not sure you can take an empty `string_view` as `NULL`. That seems like it'll cause people problems. If I used that I think many of our tests would fail (where database columns aren't nullable).

**Comment by jtv** [comment] 2019-09-01 15:52
Well wait...  There _is_ a difference between an empty `string_view` and a null one, isn't there?

**Comment by KayEss** [comment] 2019-09-01 15:54
That's very unclear to me.

```cpp
std::string_view empty{""}, null{};
```

That distinction looks likely to cause to some problems to me, even if it were g'teed by the standard (no idea on that point).

**Comment by jtv** [comment] 2019-09-01 16:01
I haven't checked the standard itself, but cppreference does say that in the first case, `empty.data()` will point to your empty string.

Consider the ways to construct a string view with a null data pointer.  One way is a separate data path like you're doing here, in which case it seems perfectly fair to me that you statically meant to construct a null value.  The other is to pass a null string pointer, which to me trivially implies nullness...

**Comment by jtv** [comment] 2019-09-01 16:03
I'm not actually sure you're _supposed_ to construct a string view from a null pointer, to be honest   It has to be a valid range, but when length is zero, nothing needs to be actually addressable, right?

**Comment by KayEss** [comment] 2019-09-02 10:45
I tried this little program:

```cpp
#include <iostream>
#include <string>
#include <string_view>

int main() {
    std::string empty1;
    std::cout << "String " << static_cast<void const *>(static_cast<std::string_view>(empty1).data()) << '\n';
    std::string_view empty2;
    std::cout << "String view " << static_cast<void const *>(empty2.data()) << '\n';
    std::cout << "Equal " << (empty2 == std::string_view{""} ? "yes" : "no") << '\n';
}
```
Which gives the following outputs on my machine:

```
$ clang++ -std=c++17 str.cpp -o str && ./str
String 0x7ffc6317ee90
String view 0
Equal yes
$ g++ -std=c++17 str.cpp -o str && ./str
String 0x7ffec87d8cc0
String view 0
Equal yes
```

So the default constructor for a `string` and a `string_view` work differently, but of course the "null" string view and the empty string view must compare equal. According to this https://en.cppreference.com/w/cpp/string/basic_string/data the standard does guarantee that `string` at least will return a non-`nullptr` pointer even if the string is empty.

It still feels a little bit too subtle of an API for me. And I'll have to double check our string never uses a `nullptr` for an empty string.

**Closed** 2019-09-02 11:43 UTC

**Comment by jtv** [comment] 2019-09-02 20:15
Hmmm....  Okay, I'll see if I can change that.  I don't think I actually _rely_ on it anywhere.

**Comment by jtv** [comment] 2019-09-02 20:30
Done.
