### ISSUE TITLE
PostgreSQL targets should be PUBLIC

### ISSUE THREAD

**Issue by codentary** [jtv/libpqxx#431] opened 2021-03-28 12:40 UTC
I see that the `libpq` include paths and the libs are private so they don't propagate to cmake projects that use the `libpqxx::pqxx` target:

```
target_include_directories(${tgt} 
    ...
    PRIVATE   ${PostgreSQL_INCLUDE_DIRS})

target_link_libraries(${tgt} PRIVATE ${PostgreSQL_LIBRARIES})
```

Because of this I ran into [this](https://stackoverflow.com/questions/66839585/undefined-reference-when-linking-libpq-in-c-project/66841247#66841247) issue.
I don't get why they would be `PRIVATE`, what is the point of importing the `libpqxx::pqxx` target but not wanting also all the dependencies from `PostgreSQL::PostgreSQL`.

**Comment by jtv** [comment] 2021-03-28 13:05
I'm not familiar enough with CMake, but it may be something to do with the
fact that you don't need the libpq headers to compile libpqxx clients.  You
need them to build libpqxx itself, but the libpqxx headers do not include
any libpq headers.

**Comment by KayEss** [comment] 2021-03-28 13:47
> you don't need the libpq headers to compile libpqxx clients

This is right. If you find that you want to access the libpq headers then you can add that as an explicit dependency, but it's cleaner for most clients not to have the extra include path

**Comment by tt4g** [comment] 2021-03-28 13:48
CMake dependencies list the elements required to build the library or the application that uses the library.
Dependencies that are required at runtime are not listed.

pqxx acts as a wrapper for libpq, so you shouldn't need to add any include paths or link libraries unless you are calling libpq functions directly.

**Comment by codentary** [comment] 2021-03-28 18:27
Ok, for the `include paths` it make sense as you should net need to include `libpq headers` directly, but what about the `libpq libs` - the list of `target_link_libraries` are also needed by the client off `libpqxx`. This was actually my issue.

**Comment by codentary** [comment] 2021-03-28 18:56
To clarify in case you did not check the stackoverflow post, my issue was that I installed `libpqxx` with `vcpkg` and added it to my project like so:
```cmake
...
find_package(OpenSSL REQUIRED) 
find_package(libpqxx CONFIG REQUIRED)
...
target_link_libraries(${PROJECT_NAME}
                        PRIVATE OpenSSL::SSL OpenSSL::Crypto
                        PRIVATE libpqxx::pqxx)
```

This was not enough as I was getting `undefined references` for some functions used in `libpq` which were as I found out later, part of 2 extra postgres libs: `libpgport.a` and `libpgcommon.a`
So I had to explicitly link those 2 libs to my target, but not `libpq`:
```camke
...
find_package(OpenSSL REQUIRED) 
#find_package(PostgreSQL REQUIRED) # Not needed (it will duplicate the libs)
find_package(libpqxx CONFIG REQUIRED)
...
target_link_libraries(${PROJECT_NAME}
                        PRIVATE libpqxx::pqxx
                        PostgreSQL::PostgreSQL    # This expands to `libpq.a`, `libpgport.a` and `libpgcommon.a` but `libpq.a` is already added by importing the target `libpqxx::pqxx`
                        PRIVATE OpenSSL::SSL 
                        PRIVATE OpenSSL::Crypto)
```

**Comment by jtv** [comment] 2021-04-06 13:32
Does that mean that we need to change the `target_link_libraries` call in libpqxx's own CMakeLists.txt?

Right now we link `${PostgreSQL_LIBRARIES}`...   Will we need to replace that with `PostgreSQL::PostgreSQL`, `OpenSSL::SSL`, and `OpenSSL::Crypto`?  Or could it be that the setting for `PostgreSQL_LIBRARIES` was somehow incomplete?

As @ttg noted, I don't use CMake all that much myself.

**Comment by tt4g** [comment] 2021-04-06 14:22
I am not a native speaker, so long English sentences may be unnatural.


There is no reason why `target_link_libraries()` should be `PUBLIC` (or `INTERFACE`) if no libpq header files such as `libpq-fe.h` or libpq symbols appear in the pqxx header files.

And it is hard to understand, but when link pqxx installed by CMake, libraries declared as `PRIVATE` in `target_link_libraries()` are automatically added to the link target.
The information of pqxx dependency libraries is recorded as a dependency tree in `libpqxx-targets.cmake` installed by the `export()` function.
CMake reads the dependency information from `libpqxx-targets.cmake` when it finds the pqxx library with `find_package(libpqxx)`, and uses `target_link_libraries(${your_target} libpqxx::pqxx)` to add pqxx and all dependent libraries to the target link.

Probably, this problem is caused by installing pqxx by `vcpkg`.
You should not have this problem with pqxx installed by CMake.

---

Addition: Here is the definition of how CMake generates `libpqxx-targets.cmake`. 
Official documentation: https://cmake.org/cmake/help/latest/command/install.html#install-export

`install(TARGETS ${tgt} EXPORT libpqxx-targets ` specifies which CMake targets should have their dependency trees recorded in `libpqxx-targets.cmake` when pqxx is installed.

https://github.com/jtv/libpqxx/blob/cbd2b35ef5bce8a1fc8bfd1efd804d965976ce23/src/CMakeLists.txt#L33-L37

Dependency libraries recorded in the dependency tree here include those declared as `PRIVATE` in `target_link_libraries()`.
This is because otherwise a link error will occur when linking the installed libraries.
Scopes such as `PRIVATE` and `PUBLIC` in `target_link_libraries()` mean that they will work during their build, but once the library is installed, everything will be `PUBLIC`.

The following CMake code defines that `libpqxx-targets` will be installed in the `/cmake/libpqxx` directory.
`libpqxx-targets.cmake` stores all the pqxx dependency tree information recorded by `install(TARGETS ${tgt} EXPORT libpqxx-targets`.
With this installation definition, CMake can find the `libpqxx-targets.cmake` installed with pqxx.

https://github.com/jtv/libpqxx/blob/cbd2b35ef5bce8a1fc8bfd1efd804d965976ce23/CMakeLists.txt#L48-L58

**Comment by tt4g** [comment] 2021-04-06 14:26
I think the reason The reason `PostgreSQL_LIBRARIES` is used for `target_link_libraries` instead of `PostgreSQL::PostgreSQL` (which is called the CMake target) is that the old CMake did not define `PostgreSQL::PostgreSQL`.
`PostgreSQL_LIBRARIES` has been defined since the old CMake.

**Comment by jtv** [comment] 2021-05-12 08:44
Is there anything more we can do about this ticket?

CMake seems to be in a difficult phase, when it comes to postgres.  It looks as if CMake only started supporting PostgreSQL 13 fairly recently, so e.g. the CMake that comes with Ubuntu 21.04 does not support the version of postgres on the same system.  That's awful, but best resolved by upstream upgrades I think.

**Comment by jtv** [comment] 2021-05-12 09:50
Thanks.  I'll close it then.

**Closed by jtv** 2021-05-12 09:50 UTC

**Comment by lili2012** [comment] 2021-10-21 08:30
> ```cmake
> find_package(OpenSSL REQUIRED) 
> ```

I come across the same problem after I install libpq and postgres by vcpkg. 
target_link_libraries(${PROJECT_NAME} PUBLIC PostgreSQL::PostgreSQL)
target_link_libraries(${PROJECT_NAME} PUBLIC libpqxx::pqxx)
I think public here is not right. 
finally I comment PostgreSQL::PostgreSQL and found libpqxx::pqx can be linked private.
#target_link_libraries(${PROJECT_NAME} PUBLIC PostgreSQL::PostgreSQL)
target_link_libraries(${PROJECT_NAME} PRIVATE libpqxx::pqxx)
Now the link errors dispeared.

**Comment by KayEss** [comment] 2021-10-21 08:36
> Now the link errors dispeare

Specifically which link errors?
