### ISSUE TITLE
Test failure on gcc release builds

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#259] opened 2020-01-16 06:22 UTC
I'm getting this on Travis now for our build:

```
FAILED: : && /usr/bin/g++-8  -O3 -DNDEBUG   libpqxx/test/CMakeFiles/runner.dir/runner.cxx.o libpqxx/test/CMakeFiles/runner.dir/test00.cxx.o libpqxx/test/CMakeFiles/runner.dir/test01.cxx.o libpqxx/test/CMakeFiles/runner.dir/test02.cxx.o libpqxx/test/CMakeFiles/runner.dir/test04.cxx.o libpqxx/test/CMakeFiles/runner.dir/test07.cxx.o libpqxx/test/CMakeFiles/runner.dir/test10.cxx.o libpqxx/test/CMakeFiles/runner.dir/test11.cxx.o libpqxx/test/CMakeFiles/runner.dir/test12.cxx.o libpqxx/test/CMakeFiles/runner.dir/test13.cxx.o libpqxx/test/CMakeFiles/runner.dir/test14.cxx.o libpqxx/test/CMakeFiles/runner.dir/test16.cxx.o libpqxx/test/CMakeFiles/runner.dir/test17.cxx.o libpqxx/test/CMakeFiles/runner.dir/test18.cxx.o libpqxx/test/CMakeFiles/runner.dir/test20.cxx.o libpqxx/test/CMakeFiles/runner.dir/test21.cxx.o libpqxx/test/CMakeFiles/runner.dir/test26.cxx.o libpqxx/test/CMakeFiles/runner.dir/test29.cxx.o libpqxx/test/CMakeFiles/runner.dir/test30.cxx.o libpqxx/test/CMakeFiles/runner.dir/test31.cxx.o libpqxx/test/CMakeFiles/runner.dir/test32.cxx.o libpqxx/test/CMakeFiles/runner.dir/test37.cxx.o libpqxx/test/CMakeFiles/runner.dir/test39.cxx.o libpqxx/test/CMakeFiles/runner.dir/test46.cxx.o libpqxx/test/CMakeFiles/runner.dir/test48.cxx.o libpqxx/test/CMakeFiles/runner.dir/test49.cxx.o libpqxx/test/CMakeFiles/runner.dir/test50.cxx.o libpqxx/test/CMakeFiles/runner.dir/test51.cxx.o libpqxx/test/CMakeFiles/runner.dir/test52.cxx.o libpqxx/test/CMakeFiles/runner.dir/test53.cxx.o libpqxx/test/CMakeFiles/runner.dir/test54.cxx.o libpqxx/test/CMakeFiles/runner.dir/test55.cxx.o libpqxx/test/CMakeFiles/runner.dir/test56.cxx.o libpqxx/test/CMakeFiles/runner.dir/test57.cxx.o libpqxx/test/CMakeFiles/runner.dir/test58.cxx.o libpqxx/test/CMakeFiles/runner.dir/test59.cxx.o libpqxx/test/CMakeFiles/runner.dir/test60.cxx.o libpqxx/test/CMakeFiles/runner.dir/test61.cxx.o libpqxx/test/CMakeFiles/runner.dir/test62.cxx.o libpqxx/test/CMakeFiles/runner.dir/test69.cxx.o libpqxx/test/CMakeFiles/runner.dir/test70.cxx.o libpqxx/test/CMakeFiles/runner.dir/test71.cxx.o libpqxx/test/CMakeFiles/runner.dir/test72.cxx.o libpqxx/test/CMakeFiles/runner.dir/test74.cxx.o libpqxx/test/CMakeFiles/runner.dir/test75.cxx.o libpqxx/test/CMakeFiles/runner.dir/test76.cxx.o libpqxx/test/CMakeFiles/runner.dir/test77.cxx.o libpqxx/test/CMakeFiles/runner.dir/test78.cxx.o libpqxx/test/CMakeFiles/runner.dir/test79.cxx.o libpqxx/test/CMakeFiles/runner.dir/test82.cxx.o libpqxx/test/CMakeFiles/runner.dir/test84.cxx.o libpqxx/test/CMakeFiles/runner.dir/test87.cxx.o libpqxx/test/CMakeFiles/runner.dir/test88.cxx.o libpqxx/test/CMakeFiles/runner.dir/test89.cxx.o libpqxx/test/CMakeFiles/runner.dir/test90.cxx.o libpqxx/test/CMakeFiles/runner.dir/test93.cxx.o  -o libpqxx/test/runner  -Wl,-rpath,/home/travis/build/hotkit/mengmom/build.tmp/libpqxx/src libpqxx/src/libpqxx-7.0.so && :

libpqxx/test/CMakeFiles/runner.dir/test11.cxx.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > pqxx::to_string<pqxx::row>(pqxx::row const&)':

test11.cxx:(.text._ZN4pqxx9to_stringINS_3rowEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN4pqxx9to_stringINS_3rowEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x8b): undefined reference to `pqxx::test::list_row[abi:cxx11](pqxx::row)'

collect2: error: ld returned 1 exit status
```

Can we make building the tests opt in rather than opt out? If I'm building libpqxx to use it and don't want to run its tests why am I building them?

Here is the Travis link: https://travis-ci.org/hotkit/mengmom/jobs/637786985?utm_medium=notification&utm_source=email

**Comment by tt4g** [comment] 2020-01-16 07:12
> If I'm building libpqxx to use it and don't want to run its tests why am I building them?

Define CMake variable `SKIP_BUILD_TEST=ON` to skip build tests.
e.g: `cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DSKIP_BUILD_TEST=ON -G Ninja`

**Comment by KayEss** [comment] 2020-01-16 07:18
I know about that, and have turned that on for the travis tests now on this project. But real question is why is the default this way around? It just causes potential problems for people building libpqxx with no upside (like this error).

**Comment by jtv** [comment] 2020-01-16 07:56
FWIW the error message per se was another problem caused by me taking clang-tidy warnings a little too seriously last night.  Should be fixed now.

**Comment by jtv** [comment] 2020-01-21 20:49
Is there a CMake convention for whether to build the tests?  Is there supposed to be a different variable, for _enabling_ building the tests?

**Comment by tt4g** [comment] 2020-01-22 00:16
We can select a behavior of `CTest` module by CMake variable `BUILD_TESTING`.
If defined `BUILD_TESTING=ON` (default) then call `enable_testing()` in `CTest` module.

* [CTest — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/latest/module/CTest.html)
* [BUILD\_TESTING](https://cmake.org/cmake/help/latest/command/enable_testing.html)

**Comment by jtv** [comment] 2020-02-09 19:08
I suppose we're done with this bug then?  I'll close it, and if there's something that still needs doing, feel free to open a new one.

**Closed by jtv** 2020-02-09 19:08 UTC
