### ISSUE TITLE
win32 link ws2_32 dont work

### ISSUE THREAD

**Issue by bartgogo** [jtv/libpqxx#748] opened 2023-11-14 17:21 UTC
from src/CMakeLists.txt line30
```cmake
if(WIN32)
        target_link_libraries(${tgt} PUBLIC wsock32 ws2_32)
endif()
```
it didn't work on ws2_32
it has to be added manually in project CMakeLists.txt
```cmake
target_link_libraries(test pqxx libpq Ws2_32)
```
better to check it

**Comment by tt4g** [comment] 2023-11-14 20:58
What do you mean it did not work?
Are there any error messages from CMake and the compiler?

**Comment by jtv** [comment] 2023-11-14 23:29
On top of @tt4g's questions, I guess we may need to know...
* Which Windows version (or Windows compatibility layer)?
* Which compiler?
* Is this while building libpqxx, or a client application?
* Are you building libpqxx as a DLL, or as a static library?

(Some of these may be stupid questions.  I'm no CMake expert, and also it generally can't hurt to be extra clear.)

**Comment by bartgogo** [comment] 2023-11-15 00:28
on top of
using windows11,msvc to build lib from
source
in the process of the building lib
,cmake configuration has set to link ws2_32.lib

build application using pqxx failed because of link error (no found some symbols)
it turned out to be losing ws2_32.lib by searching the symbol name
the application build successfully after
target_link_libraries ws2_32

**Comment by jtv** [comment] 2023-11-15 01:21
What symbols were not found?  Perhaps you could do a build (preferably with the system set to English) and show us the errors?

Any chance it's one of those problems where one library is a Debug build and the other is a Release build?

Can you pinpoint the smallest possible difference that fixes it for you?  What's the closest you can get to the original CMakeLists.txt that still fixes the problem?

**Comment by bartgogo** [comment] 2023-11-15 01:52
ok
i try it later

**Comment by tt4g** [comment] 2023-11-15 03:31
My guess is that `CMakeLists.txt` is missing `find_package(libpqxx)`.
If `find_packate(libpqxx)` is missing, CMake will recognize `pqxx` as just a string, and dependent libraries will not be added to the link target.

**Comment by bartgogo** [comment] 2023-11-15 03:53
**myown test project**
```cmake
cmake_minimum_required(VERSION 3.5)
project(test)
set(CMAKE_CXX_STANDARD 20)
include_directories("C:/Program Files (x86)/libpqxx/include")
link_directories("C:/Program Files (x86)/libpqxx/lib")
add_executable(test test.cpp)
target_link_libraries(test pqxx libpq)
```

```command
Directory: C:\Program Files (x86)\libpqxx\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         11/4/2023   4:55 PM                cmake
d-----        11/15/2023  11:07 AM                pkgconfig
-a----         8/10/2023   6:51 PM          35566 libpq.lib
-a----        11/15/2023  11:23 AM        7391666 pqxx.lib
the libpq.lib is a copy of Postgresql lib
```
Clion build
```error
LINK: command "E:\Visual Studio\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\link.exe /nologo CMakeFiles\test.dir\test.cpp.obj /out:test.exe /implib:test.lib /pdb:test.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console -LIBPATH:C:\PROGRA~2\libpqxx\lib pqxx.lib libpq.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST:EMBED,ID=1" failed (exit code 1120) with the following output:
pqxx.lib(connection.cxx.obj) : error LNK2019: �޷��������ⲿ���� __imp_ioctlsocket������ "public: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) �������˸÷���
pqxx.lib(connection.cxx.obj) : error LNK2019: �޷��������ⲿ���� __imp_WSAGetLastError������ "public: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) �������˸÷���
pqxx.lib(wait.cxx.obj) : error LNK2001: �޷��������ⲿ���� __imp_WSAGetLastError
pqxx.lib(wait.cxx.obj) : error LNK2019: �޷��������ⲿ���� __imp_WSAPoll������ "void __cdecl pqxx::internal::wait_fd(int,bool,bool,unsigned int,unsigned int)" (?wait_fd@internal@pqxx@@YAXH_N0II@Z) �������˸÷���
test.exe : fatal error LNK1120: 3 ���޷��������ⲿ����
ninja: build stopped: subcommand failed.

```
the libpqxx is a MD release version
the test project is the same
successfuly built by adding `target_link_libraries(test pqxx libpq WS2_32)`

**Comment by tt4g** [comment] 2023-11-15 10:34
As commented [here](https://github.com/jtv/libpqxx/issues/748#issuecomment-1811754322), `find_package(libpqxx)` is missing.
`pqxx libpq` is recognized as just a string and passed to the linker, so pqxx dependent libraries are not automatically linked.

If you want to take advantage of CMake's features to automatically add dependent libraries to the linker, please add `find_package(libpqxx)`.

```diff
 cmake_minimum_required(VERSION 3.5)
 project(test)
 set(CMAKE_CXX_STANDARD 20)
-include_directories("C:/Program Files (x86)/libpqxx/include")
-link_directories("C:/Program Files (x86)/libpqxx/lib")
+find_package(libpqxx REQUIRED)
 add_executable(test test.cpp)
-target_link_libraries(test pqxx libpq)
+target_link_libraries(test pqxx)
```

**Comment by bartgogo** [comment] 2023-11-16 06:25
there's no such Findlibpqxx.config things
cannot use find_package to locate libpqxx

**Comment by tt4g** [comment] 2023-11-16 08:59
> there's no such Findlibpqxx.config things

This means that libpqxx is not installed using CMake.
This is not a bug, since it is your role to set libpqxx dependencies installed without CMake as link targets.

**Comment by KayEss** [comment] 2023-11-16 09:42
Presuming you're building libpqxx yourself, you'll probably find it easier to just add the libpqxx directory to your project using `add_subdirectory`. That way you will automatically get the correct build settings for things like release/debug and link options.

**Comment by bartgogo** [comment] 2023-11-16 09:44
cmake --install . being used
path set to pathto/lib/cmake/libpqxx
findpackage didnt work
so how to properly set the package？

**Comment by tt4g** [comment] 2023-11-16 09:54
Perhaps `find_package(pqxx REQUIRED)` might work.

If you are installing using the `cmake --install` command, you should have `<PacakgeName>Config.cmake` (or `<LowercasePackageName>-config.cmake`).
`find_package(libpqxx)` will look for this file.
See: https://cmake.org/cmake/help/v3.28/guide/using-dependencies/index.html#config-file-packages

**Comment by bartgogo** [comment] 2023-11-16 15:23
the whole things done
I got it
![save](https://github.com/jtv/libpqxx/assets/150788413/cbf22249-a5fa-4a41-bee9-8454780c3572)
First thing first
We need to set CMAKE_PREFIX_PATH or CMAKE_MODULE_PATH Manually in order to find The Package
make sure the `libpqxx-config.cmake ` exists in the path

Second
since it's called `libpqxx::pqxx` in the `libpqxx-config.cmake` 
it has to be `libpqxx::pqxx` when it comes to target_link_libraries
And done,no more dependencies error

Recommend to add these in the first step of example

**Comment by tt4g** [comment] 2023-11-16 21:02
The drive `F:` is not the default installation path for CMake, so it is not the package search path.
It is caused by your customized CMake configuration.

**Comment by jtv** [comment] 2023-11-17 12:23
Glad it's solved though!

Small pedantic note: it's "postgres," not "postgre."  :-)

**Comment by jtv** [comment] 2023-11-26 23:26
Closing this ticket.  It will still be here, so others searching for solutions for similar problems can still find it.

**Closed by jtv** 2023-11-26 23:26 UTC
