### ISSUE TITLE
Need help resolving connection issues.

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#546] opened 2022-03-11 22:18 UTC
Hi,
 I am getting the below mentioned error ,
My code does the following 
while (iterate over rs ){ 
1)makes a connection 
2)sets a parameterized query 
3) updates some table
4) disconnects 
}

FATAL:  remaining connection slots are reserved for non-replication superuser connections

Note : I can't make the connection outside the while loop as it breaks existing code structure.
Also please point me to some good articles/links that could help me resolve this. 

Any work around would be great help.
Thank you 
dpasha52

**Comment by tt4g** [comment] 2022-03-11 23:22
The cause is that you are creating more connections than the maximum number of database connections.
Please increase the `max_connections` parameter in `postgresql.conf`.

Note the number of connections specified in `superuser_reserved_connections` is reserved for the super user (`postgres`).
The maximum number of connections that can be used by non-superusers is limited to `max_connections - superuser_reserved_connections`.

See: https://www.postgresql.org/docs/12/runtime-config-connection.html

**Comment by jtv** [comment] 2022-03-12 09:11
Yup, you're simply making too many connections.

But why are you making a new connection for every iteration of your loop?
It usually makes sense to keep the same connection object and use it for
multiple commands.  Your *transaction* object should generally be
short-lived, but the *connection* can live for a long time.

If the loop runs for so long that dropped connections become a problem, you
can build in an exception handler for pqxx::broken_connection that replaces
your connection with a new one and re-does the last iteration.

Or, as a simple compromise, you could turn your loop into an outer loop
that creates a new connection every time, but inside that have a nested
inner loop that does a number of iterations of the actual work, using a
single connection.

**Comment by leonardsangoroh** [comment] 2022-03-12 13:42
I'm not sure whether the connection instance should be in a loop

**Comment by jtv** [comment] 2022-03-12 13:59
Yeah, it sounds a bit unusual, and inefficient.  Establishing a connection
can be quite slow compared to the cost of executing a simple query.

**Comment by dpasha52** [comment] 2022-03-15 14:52
Thank you for the suggestions. will look into it.and find a way to fix it. 
Thank you
Dpasha52.

**Comment by jtv** [comment] 2022-03-24 00:09
Probably time to close this issue.  Feel free to file a new one if you run into problems again.

**Comment by dpasha52** [comment] 2022-03-27 15:50
As a work around to avoid changes to existent code I am only creating connection once and making a static connection object that can be used by other objects.

example 
class abc {
static pqxx::connection * c=NULL;
}
abc::make_conne(){
NOTE://initialize it only once done defensive prog to assure the same.
if ( is connected) {
    string conn1;
    new pqxx::connection(conn1);
}

}

somefunction () {
ABC obj ;
obj.makeconnection();
obj.exec_params()

}

Now I am getting this error on trying to execute query using the static connection object created only once by other dependent code 
Could not obtain client encoding : not connected.

Excuse the crude pseudo code written
Any advice/links on this would be would be great help.
Thank you 
dpasha52

**Comment by dpasha52** [comment] 2022-03-27 17:45
Also tried is_open() which returns false and make a connection again, still facing this issue.

**Comment by jtv** [comment] 2022-03-27 18:08
Is it possible that the connection attempt threw an exception that you didn't see for some reason?

**Comment by dpasha52** [comment] 2022-03-27 19:07
Let me check, although I see this error in the catch block.

**Comment by tt4g** [comment] 2022-03-27 21:56
Perhaps `max_connections` in PostgreSQL configuration is set to a very low value. Can you check the setting?

**Comment by jtv** [comment] 2022-03-28 08:19
@dpasha52 I understand that the error you're seeing is also an exception, but what I'm driving at is the possibility that maybe there was an _earlier_ exception, at the time when you created the connection.

Another possibility is a race condition.  Is your application multi-threaded?  Maybe one thread is accessing the connection while another is still busy initialising it?

**Comment by dpasha52** [comment] 2022-03-28 13:08
If so do I need mutexes or some sort of semaphore.?
Thank you
dpasha52

**Comment by jtv** [comment] 2022-03-28 13:16
Yes, a mutex would help.

In general, when you do anything non-const with a pqxx object, you'll have
to make sure that nothing else accesses that object at the same time.

**Comment by dpasha52** [comment] 2022-03-29 08:39
Thank you for the help, it seems to be working for now.But i'd like to keep this issue open for a few more days.

**Comment by dpasha52** [comment] 2022-03-30 05:59
We can close this issue.

**Comment by jtv** [comment] 2022-03-30 08:14
OK, thanks for letting me know.

**Closed by jtv** 2022-03-30 08:14 UTC
