### ISSUE TITLE
Converting field to double throws exception

### ISSUE THREAD

**Issue by grunk** [jtv/libpqxx#159] opened 2019-02-08 14:29 UTC
Hi,

i'm trying to get some data from a postgresql table and i'm having trouble with a conversion to double : 

```
for (auto row : r) {
	c.date_add = row[2].as<std::string>();
	c.latitude = row[3].as<double>(); // throw Could not convert string to numeric value : '45.02564'
}
```
The database field have "double precision" type.

i 've work my way around the problem by doing : 
`c.latitude = std::stod(row[3].as<std::string>());`
but i'd rather get it working the proper way.

I'm wondering if the locale can be at fault here ? My default locale is french where a decimal number is in theory written with a comma (45,02564).

I'm working with postgres 11 , on windows 10 et Vs 2015

**Comment by jtv** [comment] 2019-02-08 15:38
That _does_ sound like it might be a locale problem...  And the funny thing is, `std::stof` is locale-sensitive.  Communication between the database and libpqxx should be entirely un-localised.

Could you check that the string you get from `row[3].as<std::string>()` really uses a dot, and not a comma?  It'll help us narrow down the  search area.

**Comment by grunk** [comment] 2019-02-08 16:30
`row[3].as<std::string>()` return the string with the dot. I never use comma separated number.

**Comment by jtv** [comment] 2019-02-08 19:47
Maybe you could give me the exact string, just in case I can reproduce the problem?  Might it be a case of excessive precision perhaps?

**Comment by grunk** [comment] 2019-02-08 22:17
The exact string is "45.02564" , it's a gps coordinate. I'll confirm on monday but i reckon i have the same problem with much less precision like "4.6"

**Comment by jtv** [comment] 2019-02-09 23:38
Couldn't reproduce the problem with gcc and a French locale...  :-/

My best guess so far is that setting the C locale on a stringstream didn't work.  Could the problem be that imbuing it with `std::locale::classic()` is not having an effect?

**Comment by tt4g** [comment] 2019-02-10 00:35
For your record, I couldn't reproduce problem with VIsual Studio 2017(C++14):

```cpp
#include <locale>
#include <iostream>
#include <sstream>

int main()
{
    std::locale::global(std::locale("french"));

    // strconv.cxx: dumb_stringstream
    std::stringstream ss;
    ss.imbue(std::locale::classic());
    ss.precision(std::numeric_limits<double>::max_digits10);

    std::cout << "ss.locale: " << ss.getloc().name() << std::endl; // stringstream.locale: C

    // strconv.cxx: from_string_float
    ss.seekg(0);
    ss.clear();
    ss.str("45.02564");
    double result;
    bool ok = static_cast<bool>(ss >> result);

    if (ok) {
        std::cout << "result: " << result << std::endl; // convert: 45.0256
    } else {
        std::cout << "failed" << std::endl;
    }

    return 0;
}
```

**Comment by jtv** [comment] 2019-02-10 13:44
That sounds like it's a bug in their standard library that got fixed in 2017...  :/

**Comment by grunk** [comment] 2019-02-11 07:54
Running the previous snippet on VS 2015 works fine : 

> ss.locale: C
> result: 45.0256

Using the same method to cast from string works also fine : 

```
for (auto row : r) {
    std::stringstream ss;
    ss.seekg(0);
    ss.clear();
    ss.str(row[3].as<std::string>());
    ss >> l.latitude;
}
```

But 
```
l.latitude = row[3].as<double>();
l.latitude = row[3].as<float>();
```
fails

What kind of cast is happening behind the scen when i write `row[3].as<double>()` ?

**Comment by tt4g** [comment] 2019-02-11 11:11
The locale of the PostgreSQL server may be involved.

@grunk Can you check locale of PostgreSQL servier？

e.g: 
```sql
$ SELECT name, setting, context FROM pg_settings WHERE name LIKE 'lc%';
name | setting | context
-------------+-------------+-----------
lc_collate | C | internal
lc_ctype | C | internal
lc_messages | C | superuser
lc_monetary | C | user
lc_numeric | C | user
lc_time | C | user
```

**Comment by grunk** [comment] 2019-02-11 12:22
Here is the result.
I did not change anything to postgresql config, it the default just after the install.

"lc_collate"	"French_France.1252"	"internal"
"lc_ctype"	"French_France.1252"	"internal"
"lc_messages"	"French_France.1252"	"superuser"
"lc_monetary"	"French_France.1252"	"user"
"lc_numeric"	"French_France.1252"	"user"
"lc_time"	"French_France.1252"	"user"

**Comment by tt4g** [comment] 2019-02-11 14:20
It seems that the locale of `LC_NUMERIC` is in French.
Please try changing the locale once.

e.g.:
```cpp
pqxx::connection conn;
pqxx::work w(conn);

w.exec("SET LC_NUMERIC= 'C'"); // change numeric locale to c

// try `SELECT ...` and `as<double>()` here.
```

I'm not sure if it's affected by the locale settings of the server.
If the locale causes it, I think that error will not occur.

**Comment by jtv** [comment] 2019-02-11 15:24
TBH it never occurred to me that anyone might run the database _server_ in a different locale.  But it shouldn't make a difference — postgres does not localise numbers, dates, and so on exactly so that client software can decode them.

By the way, I'm not sure Windows has a "C" locale _under that exact name._  That's one reason to use `std::locale::classic()`.

**Comment by grunk** [comment] 2019-02-11 16:27
> It seems that the locale of `LC_NUMERIC` is in French.
Please try changing the locale once.

It'working when i force the local as you suggested.

> TBH it never occurred to me that anyone might run the database _server_ in a different locale
It's the configuration i get "out of the box" from postgres installer. Maybe i can enforce the locale when i create my database or my tables.

I guess we can close the issue, pqxx don't seems to be at fault here no ?

**Comment by jtv** [comment] 2019-02-11 16:55
Well...  the conversion still _should_ work.  Did you say (near the beginning of this ticket) that the compiler version made a difference?

**Comment by grunk** [comment] 2019-02-11 20:59
I don't think so because the sample from @tt4g works on vs2015. I can't really test an other version of msvc anyway.
Does the sample from tt4g do the same thing as libpqxx does when we ask for a cast ?

**Comment by tt4g** [comment] 2019-02-12 04:42
@jtv Are you confused by my comments? If so, I'm sorry.

I guessed that the difference between 'LC_NUMERIC' of the server and the client (this difference is because it is often difficult problems).

No error occurred after `SET LC_NUMERIC=C` of PostgreSQL server, 
I think the data sent from the server is being converted (e.g. `SELECT to_number(latitude, 'FM99D99999')`).

**Comment by grunk** [comment] 2019-02-12 07:58
I probably use the wrong code yesterday , because after further testing setting LC_NUMERIC to 'C' still give me the same error. I guess i was using a part of my code where i still had my custom cast.
Sorry for misleading you :(

Here is what i have tested : 

```
std::stringstream sqlbuilder;
sqlbuilder << "SELECT id,date_c,date_a,latitude,longitude FROM " << mTable;

BuildQueryFromParams(sqlbuilder, params); // Add params to query

SortQuery(sqlbuilder, orderBy);

LimitQuery(sqlbuilder, limit, offset);

std::string sql = sqlbuilder.str();

pqxx::work w(mC);

w.exec("SET LC_NUMERIC= 'C'");

try {
    mC.prepare("search", sql);
    pqxx::prepare::invocation w_invocation = w.prepared("search_lecture");
    ParametrizeQuery(params, w_invocation); // Bind params
    pqxx::result r = w_invocation.exec();

    for (auto row : r) {
        l.id = row[0].as<int>();
        l.date_c = row[1].as<std::string>();
        l.date_a = row[2].as<std::string>();
        l.latitude = row[3].as<double>());
        l.longitude = row[4].as<double>()); 
    }
}
```

**Comment by jtv** [comment] 2019-02-12 08:08
@tt4g I may have picked up the wrong impression...  We'll live.  :-)

@grunk No, I don't see anything that libpqxx does differently for `field.as<>()` than what you do in your test.  Nothing that'll matter, anyway.  It ultimately boils down to `string_traits<>::from_string`.

What exactly did you mean by "custom cast"?

(By the way, there's a more modern API for parameterised statements now: you can just do things like `w.exec_params("search", param1, param2, param3);` directly, without any `invocation` object.)

**Comment by jtv** [comment] 2019-02-12 08:19
Oh, the "custom cast" is the `std::stod` call, right?

**Comment by tt4g** [comment] 2019-02-12 10:34
@grunk The names of the prepared statements do not match (typo?): `mC.prepare("search", sql);` and `w.prepared("search_lecture");`

Your testing source is defined `search`, but the executed SQL looks like` search_lecture`.

**Comment by jtv** [comment] 2019-02-12 10:46
@grunk I just realised there is a significant difference between libpqxx's `field::as<>()` and something you tried:

    for (auto row : r) {
        std::stringstream ss;
        ss.seekg(0);
        ss.clear();
        ss.str(row[3].as<std::string>());
        ss >> l.latitude;
    }

The difference I'm thinking of is: we don't know if any error bits are set at the end!  The libpqxx version of the conversion does check this, by "casting" the stringstream to bool.  The exception happens if the stringstream is in a failure state.

Unfortunately error checking on streams is not very user-friendly.  It's given us trouble before.  I just don't know how to figure out what goes wrong inside that stringstream, but in that test snippet, maybe you could check `if (!ss)` in that loop body?  The one thing we can easily narrow down is whether it happens during the `ss.str()` call, or during the `operator >>()` call, by checking in both places.

**Comment by grunk** [comment] 2019-02-12 14:14
@tt4g Yes this is just a typo , i use the same name in both cases :)
@jtv , by "custom cast" i indeed mean using std:stod nothing fancy here 😋 .
I know about the modern api for prepared statement but in this specific case i need to loop over an unknown number of attribute to dynamically build the query and just calling `exec_params()` didn't seem possible. I use it elsewhere though.

The following code works perfectly fine. I do not trigger the error message : 
```
for (auto row : r) {
    std::stringstream ss;
    ss.seekg(0);
    ss.clear();
    ss.str(row[3].as<std::string>());
    if (!ss) {
        std::cout << "ERROR STR";
    }
    ss >> l.latitude;
    if (!ss) {
        std::cout << "ERROR OPERATOR >>";
    }
}
```

**Comment by jtv** [comment] 2019-02-12 15:24
There goes my best theory so far.  And you're really building and linking against libpqxx 6.3.1, not against some other version that might be installed on your system?  We did have a problem with Visual Studio not so long ago where the `clear()` happened _before_ the `seekg(0)`, and for some reason that registered an error.

**Comment by grunk** [comment] 2019-02-12 16:50
I'm using libpqxx 6.2.5 which was the last one available the last time i compiled it. I can try the 6.3.x if it's still compatible with C++11.

**Comment by jtv** [comment] 2019-02-12 17:00
In that case this is probably just #124 / #125!

Yes, the 6.x series of libpqxx is still compatible with C++11.  In 7.0 we're going with C++17 as the baseline, and hopefully replacing all this code with `std::to_chars` and `std::from_chars`...

**Comment by tt4g** [comment] 2019-02-12 20:53
Oops! I should have checked the version earlier.

The sample code that We tried is version 6.3.0 later...I am sorry that I caused you trouble.

**Comment by jtv** [comment] 2019-02-12 22:00
Well, glad the problem is solved at least.  :-D

**Closed by jtv** 2019-02-12 22:00 UTC

**Comment by grunk** [comment] 2019-02-15 14:06
Just to follow up , i updated to 6.3.1 and the bug is gone. I should have specified the version i used in my first post.

Thanks for your time ;)

**Comment by jtv** [comment] 2019-02-15 15:55
Thanks.
