### ISSUE TITLE
PQXX Streams: Reading of table data failed: no COPY in progress

### ISSUE THREAD

**Issue by jrch2k20** [jtv/libpqxx#423] opened 2021-03-10 01:14 UTC
Hi, i'm using latest libpqxx release and i'm trying to use streams but i got this error no matter what i do, is this known?

terminate called after throwing an instance of 'pqxx::failure'
  what():  Reading of table data failed: no COPY in progress

`for (auto [bind, protocol, method, cipher, cert_file, priv_key_file] : tx.stream<std::string_view, std::string_view, std::string_view, std::string_view, std::string_view, std::string_view>(R"(SELECT bind,protocol::TEXT,method::TEXT,cipher,cert_file,priv_key_file FROM ps_transports)")) {
    ... code
    }`

TYVM for your time

**Comment by tt4g** [comment] 2021-03-10 02:47
"no COPY in progress" is an error message indicating that no stream data has been sent from the server.
Make sure that the connection to the PostgreSQL server is established.
Also, try to fetch the data from the `ps_transports` table in some other way than a stream.

**Comment by jrch2k20** [comment] 2021-03-10 03:28
i'll try tcp connection instead of socket and see otherwise i'll rollback to the usual pqxx::result method that was working before.

Tyvm for your answer

**Comment by tt4g** [comment] 2021-03-10 04:20
It seems that `tx.stream()` sends a `COPY ... TO STDOUT` statement to the server.
Try `psql` to see if `COPY (SELECT bind,protocol::TEXT,method::TEXT,cipher,cert_file,priv_key_file FROM ps_transports) TO STDOUT` returns any results.

https://github.com/jtv/libpqxx/blob/7eed2f24df244f3987b5845be8650008aa953cc4/src/stream_from.cxx#L36-L42

**Comment by jtv** [comment] 2021-03-10 06:10
Could you fix the code block so it gets rendered correctly?  You can quote
it using triple backquotes, or indent the whole block.

**Comment by jtv** [comment] 2021-03-10 06:19
From what I can see everything looks OK...  I'm thinking maybe there's an
error in setting up the stream that can't be reported for some reason, but
I don't yet see what that could be.

What else happens in `tx` before this point?  And as @tt4g pointed out,
it'd be helpful to know whether the exact same query works (1) by itself,
and (2) in a COPY statement.

**Comment by jrch2k20** [comment] 2021-03-10 22:23
i just pasted this exact command into pgadmin query `COPY (SELECT bind,protocol::TEXT,method::TEXT,cipher,cert_file,priv_key_file FROM ps_transports) TO STDOUT` and got

ERROR: can't execute COPY TO: use the copy_to() method instead

As  requested the query itself works fine and was tested in the app using regular TX.exec() and pgadmin without issues

just in case i'm using 
postgres (PostgreSQL) 13.2

TYVM for your time

**Comment by jtv** [comment] 2021-03-10 22:32
Hmmm...  That may just mean that pgadmin doesn't support COPY TO because it
needs to do some additional setup to make the output go somewhere useful.
Might have more luck with psql, the basic bare-bones command line.

Still could be useful to look at context, as well.  What happens to tx in
the rest of your code, before you get to this point?

**Comment by jrch2k20** [comment] 2021-03-10 22:42
Well, basically is a smart pointer passed to that function with a pool of connections but since i doubted myself before posting here i basically created a clean function to test any possible pointer/conn state weirdness 

```
#include <pqxx/pqxx> // standard std bolier plate includes assumed

auto start_transport_validation() -> bool{
pqxx::connection c{"postgresql://my conn string"};
pqxx::work tx{c};
for (auto const& [bind, protocol, method, cipher, cert_file, priv_key_file] : tx.stream<std::string_view, std::string_view, std::string_view, std::string_view, std::string_view, std::string_view>(R"(SELECT bind,protocol::TEXT,method::TEXT,cipher,cert_file,priv_key_file FROM ps_transports)")) {
std::cout << bind << ", " << cipher << std::endl;
}
return true;
}

auto main(int argc, char* argv[]) -> int
{
 start_transport_validation();
}
```

**Comment by jtv** [comment] 2021-03-10 22:51
Remember those triple quotes though!  ;-)

**Comment by jrch2k20** [comment] 2021-03-11 03:42
This is the output from psql

COPY (SELECT bind,protocol::TEXT,method::TEXT,cipher,cert_file,priv_key_file FROM ps_transports) TO STDOUT;
0.0.0.0	udp	\N	\N	\N	\N
0.0.0.0	wss	\N	\N	\N	\N
0.0.0.0	tls	tlsv1

**Comment by jtv** [comment] 2021-03-11 06:28
So that works!

I'm scratching my head here to find any significant difference from the
unit test test_transaction_stream_from:

https://github.com/jtv/libpqxx/blob/master/test/unit/test_stream_from.cxx

**Comment by jrch2k20** [comment] 2021-03-11 23:45
beats me as well, perhaps pgsql 13 had some ninja change i guess, since i'm using ArchLinux i have the latest of the latest installed.

May something in postgresql.conf affect this?

**Comment by jrch2k20** [comment] 2021-03-11 23:55
admin:///var/lib/postgres/data/postgresql.conf
[postgresql.conf.txt](https://github.com/jtv/libpqxx/files/6126576/postgresql.conf.txt)

just in case is useful

**Comment by jtv** [comment] 2021-03-12 07:56
The only COPY-related change I see in the release notes is a fix to the handling of multibyte characters.  Does your query return any non-ASCII data?

**Comment by jrch2k20** [comment] 2021-03-12 17:18
nope, just the data i posted.

**Comment by jtv** [comment] 2021-03-12 17:39
This is driving me nuts.  Does the same query work with stream_from?

**Comment by jrch2k20** [comment] 2021-03-12 17:49
no idea, this is the first example i made for testing(i currently use the regular execs everywhere) but i can try later and see what it does

**Comment by jrch2k20** [comment] 2021-03-15 03:48
same error as stream

**Comment by jtv** [comment] 2021-03-15 17:04
Urgh.  Then it may be time to register an error handler, and capture any error or warning messages.

This is something I haven't done myself in a long time.  I'd love to overhaul its API, maybe for 8.0.  But anyway, the idea is:
 1. Derive a class from `pqxx::errorhandler`.
 2. Give it a constructor which takes a `pqxx::connection` and passes that to the `pqxx::errorhandler` constructor.
 3. Override its `virtual operator()(char const msg[])`.  Have it write the `msg` argument somewhere, e.g. to `std::cerr`.
 4. After creating the connection, create an object of your class, passing the connector to its constructor.
 5. Make sure your object is destroyed _after_ your transaction ends but _before_ your connection is destroyed.
 6. Now run the test code again and see what it says!

**Comment by jrch2k20** [comment] 2021-03-18 23:40
ok, here we go

Class:
`class  postgresql_debugger final : public pqxx::errorhandler {
public:
    explicit postgresql_debugger(pqxx::connection& conn)
        : pqxx::errorhandler(conn)
    {
    }

    ~postgresql_debugger() override = default;

    postgresql_debugger(const postgresql_debugger&) = delete;
    postgresql_debugger(postgresql_debugger&&) = delete;
    auto operator=(postgresql_debugger&&) -> postgresql_debugger& = delete;
    auto operator=(const postgresql_debugger&) -> postgresql_debugger& = delete;

    auto operator()(const char msg[]) noexcept -> bool override
    {
        std::printf("Raw Postgresql output:\n %s", msg);
        return true;
    }
};
`

Code:
pqxx::connection postgresql_client("my string");`
postgresql_debugger debugger(postgresql_client);
    auto stream = postgresql_client->stream_from(R"(SELECT user_id FROM public."Session_logs")");
    for (auto row : *stream.read_row()) {
        std::cout << row << std::endl;
    }
    stream.complete();
`

Output:
Raw Postgresql output:
 Closing transaction  with stream_from still open.
terminate called after throwing an instance of 'pqxx::failure'
  what():  Reading of table data failed: no COPY in progress

**Comment by jrch2k20** [comment] 2021-03-19 00:08
ok i had a breakthrough

if the code i pasted is on local stack it works

but this break it

       `std::shared_ptr<pqxx::connection> p_postgresql_connection = std::make_shared<pqxx::connection>(server_string.value().c_str());`

if i pass it anywhere else but only for streams, all other functionality works fine

**Comment by jrch2k20** [comment] 2021-03-19 02:50
Bingo i found the issue.

Failing code inside my library

```
template <typename... TYPE>
    [[nodiscard]] auto stream(std::string_view query)
    {
        pqxx::work work { *p_postgresql_connection };
        return work.stream<TYPE...>(query);
    }

[[nodiscard]] auto stream_from(std::string_view query)
    {
        pqxx::work work { *p_postgresql_connection };
        return pqxx::stream_from::query(work, query);
    }
```
Failing code when executing

  ```
 postgresql_debugger debugger(*postgresql_client->get_raw_connection());
    auto stream = *postgresql_client->stream_from(R"(SELECT user_id,ip_address FROM public."Session_logs")");
    for (auto row : *stream.read_row()) {
        std::cout << row << std::endl;
    }
    stream.complete();
```
Working code

  ```
  pqxx::work tx(*postgresql_client->get_raw_connection());
    postgresql_debugger debugger(*postgresql_client->get_raw_connection());
    auto stream = pqxx::stream_from::query(tx, R"(SELECT user_id,ip_address FROM public."Session_logs")");
    for (auto row : *stream.read_row()) {
        std::cout << row << std::endl;
    }
    stream.complete();
```
It seems that using pqxx::work/pqxx::stream_from::query inside my class break something for streams even tho the connection is valid but declaring pqxx::work/pqxx::stream_from::query locally do the job.

Given that i assume unlike execs, stream work like views and at return they simply lose their state completely or partially and it doesn't validate its state or assumes the query was empty

**Comment by jtv** [comment] 2021-03-19 09:50
Is your library a shared library?  I could imagine that causing some kind of trouble.  Especially with `transaction::stream()`, which (only until we go C++20 I hope) has some slightly delicate trickery to manage the stream's lifetime.

But I can't say I really understand what you're saying yet.  It looks to me as if your _working_ example starts a transaction, but your _failing_ example seems to assume that a transaction is already open.

**Comment by jtv** [comment] 2021-03-19 10:04
I'm beginning to see what you mean.  I think the problem is in a part of
the code that you didn't show: you're closing the transaction before
completing the stream.

Yes, a stream lives "inside" a transaction, so its lifetime must be fully
contained within the transaction's lifetime.  I'll try to document that
more clearly.

**Comment by jrch2k20** [comment] 2021-03-19 15:47
Yeah, by norm i don't use third party libraries directly but a class of my own that encapsulates said library(yeap, good ol .SO), that way i save myself lot of trouble later on since any change in the API breaks only that class. In this case this class have a global connection that is shared by all the transactions in that instance but all transactions are local to each wrapper functions.

It seems the exec transactions return fine since results are moved into the various pqxx::results variants and are independent of the transaction lifetime but it seems i have to find a way to manage stream result internally in the wrapper function and return a hard type or take function pointer to be sure any operation happens in the transaction's lifetime.

Well. i think this can be closed and i agree a hint on the documentation should be a good enough fix

**Comment by jtv** [comment] 2021-03-19 16:05
Glad that's solved.  Best leave the bug open though so I don't forget to
improve the documentation.

Of course there's a wider choice to be made between exec() and stream(): if
your connection fails during data transfer, exec() will just fail
completely.  With stream(), you may get an error after you've already
processed some rows that came before the error.

Sometimes you don't want to wait until you've got all rows, but the choice
mostly depends on what your application can do about a failure.

**Closed** 2021-04-23 22:45 UTC
