### ISSUE TITLE
building fail on github actions using cmake 3.30

### ISSUE THREAD

**Issue by dr3mro** [jtv/libpqxx#863] opened 2024-07-10 22:33 UTC
Unknown CMake command "cmake_determine_compile_features".
thats all, looks like cmake has changed a method name 
**https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9366**

please fix

**Comment by tt4g** [comment] 2024-07-11 03:28
Thank you for reporting, this problem already fixed #851 but not release yet).
Workaround use fixed source (fixed in d5bf7cf83d0c86c502b6b30d5f0c8dc3b3049a38).

**Comment by jtv** [comment] 2024-07-20 14:47
@dr3mro does the latest `master` fix it?

**Comment by jlnr** [comment] 2024-07-29 09:13
libpqxx 7.9.1 stopped compiling for me with the same error after both Homebrew and my Linux distro upgraded CMake to version 3.30. I can confirm that it is fixed on the latest master commit.

An official release that contains the fix would be greatly appreciated, because then package managers like Conan will pick it up.

```
% git checkout tags/7.9.1
% cmake ..                
CMake Error at cmake/config.cmake:14 (include):
  include could not find requested file:

    CMakeDetermineCompileFeatures
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


-- Found PostgreSQL: /opt/homebrew/lib/postgresql@14/libpq.dylib (found version "14.12")
-- Looking for poll
-- Looking for poll - found
CMake Error at cmake/config.cmake:42 (cmake_determine_compile_features):
  Unknown CMake command "cmake_determine_compile_features".
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


-- Configuring incomplete, errors occurred!


% git checkout master     
Previous HEAD position was c154460e Disable clang-based parsing in Doxygen. (#847)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
% cmake ..               
-- Generating config.h
-- Generating config.h - done
-- Configuring done (2.9s)
-- Generating done (0.0s)
-- Build files have been written to: [redacted]/build
```

**Comment by jtv** [comment] 2024-08-01 06:56
OK, coming up!

**Comment by jtv** [comment] 2024-08-15 13:07
@jlnr did the release solve your problem?

**Comment by dr3mro** [comment] 2024-08-15 18:04
> @jlnr did the release solve your problem?

yeah

**Comment by jtv** [comment] 2024-08-15 20:44
Okay, when we can close this ticket.

**Closed** 2024-08-15 20:44 UTC
