### ISSUE TITLE
Docs gone since 7.9

### ISSUE THREAD

**Issue by CalebCurry** [jtv/libpqxx#802] opened 2024-03-03 02:34 UTC
I noticed the docs went away going from  7.8.1 to 7.9. Now, the readthedocs page is empty.
If this is intentional as the 7.9 docs are not complete perhaps it'd be best to default to 7.8.1 docs in the meantime so users know _something_ exists. 

<img width="1071" alt="image" src="https://github.com/jtv/libpqxx/assets/13798261/f0482998-9ed1-4408-8dde-2d76d58b8305">

**Comment by jtv** [comment] 2024-03-03 12:03
No it's not intentional.  But something changed in how buildthedocs builds worked, and so the existing configuration suddenly no longer worked.  It was quite annoying.

I thought I'd fixed that.  Wasn't trivial.  But now it turns out that I still need to do more...

**Comment by jtv** [comment] 2024-03-03 12:04
By the way the docs didn't fully go away - you can still search, and find class/function documentation!

It looks as if the indexes and the Markdown docs are gone.

**Comment by alexolog** [comment] 2024-03-21 01:36
That's a problem, we are using the docs heavily.
Please fix them.  Thank you!

**Comment by jtv** [comment] 2024-03-21 17:20
I'll try, but I'm fairly ill right now.  I think the documentation build logs are publicly accessible  on readthedocs...  If so, perhaps you can have a look and see if you can find the problem.  They made some incompatible changes recently so the builds just suddenly started breaking, without any help from me.

Until then, all the documentation in there is also in the libpqxx source tree.

**Comment by jtv** [comment] 2024-03-21 17:24
Also, you should be able to build the documentation on your own machine.

**Comment by alexolog** [comment] 2024-03-21 19:43
> Also, you should be able to build the documentation on your own machine.

How do I do it?
It did not create a `doc` subdirectory when I built it.

**Comment by jtv** [comment] 2024-03-21 23:34
I haven't done it in a while because Ubuntu's packaging of Firefox no longer lets me just view a file on the local filesystem.  But it worked something like:

You may need some additional packages installed on your system - you'll have to dig around to find out which.

Configure a libpqxx build using the `configure` script.  Pass the `--with-documentation` option on the command line.

Do a regular build.  It should create the docs tree somewhere in the build tree.  If it does not, that's typically a sign that one of those packages was not installed.

**Comment by jtv** [comment] 2024-04-23 19:25
I've been trying various things by the way, but haven't succeeded yet at getting the readthedocs documentation to build properly again.  :-(

**Comment by CalebCurry** [comment] 2024-04-23 19:27
Perhaps we should just go from the raw .md files and move it over to something like docusaurus? Or even a plan readme folder? @jtv

**Comment by jtv** [comment] 2024-04-23 20:40
I was thinking I might go with mkdocs, but still on ReadTheDocs.  But frankly I feel pretty demotivated at this point.  _Something_ made an incompatible change and I'm supposed to guess what it is.

**Comment by egorpugin** [comment] 2024-04-23 20:46
Is it possible to bisect somehow?

**Comment by jtv** [comment] 2024-04-23 23:20
Bisect what though?  I don't know that I get to choose versions for all the components involved.  Nor am I sure which components might be relevant, or which versions have been running.

It _could_ be something simple, like how CircleCI seem to have just moved their genetically named config file from a custom directory into the project root.  Or it could be something that I've been doing wrong all along but that never caused quite enough trouble.  At any rate it feels like I.pretty much have to start from scratch.

One problem IIRC is that I couldn't find a reliable way to navigate the filesystem on the build slave.

**Comment by jtv** [comment] 2024-05-02 02:27
I think I've made some progress.  I can get ReadTheDocs / Sphinx / Doxygen / Breathe to generate documentation.  But it's all a single page, with the introduction all the way at the bottom.  I'll still need to find a way to control that.

Unfortunately the documentation for Breathe is driving me up the walls.  It skips the basics and goes straight into the details.  It also seems to contradict itself.  I'm sure it's alright for people who already know and don't need the documentation, but...

**Comment by tt4g** [comment] 2024-05-02 10:36
@jtv FYI. Since Read the Docs [basically uses the latest version library](https://docs.readthedocs.io/en/stable/build-default-versions.html), it seems to be recommended that the version be fixed so that the document generation is not broken by the release of a new version.

It is recommended to use [`pip-tools`](https://github.com/jazzband/pip-tools) to list the libraries and versions to be installed in `requirements.txt`.
See: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pin-your-transitive-dependencies

**Comment by jtv** [comment] 2024-05-02 10:37
Will certainly do that when I get it working again @tt4g .

**Comment by jtv** [comment] 2024-05-04 00:38
I've sort of got documentation, but not in a nice way...  It's all in one page, with the introduction all the way at the bottom.

**Comment by jtv** [comment] 2024-05-07 20:33
Thanks for the tip about `master_doc` @tt4g — but weirdly, _neither_ `master_doc` _nor_ `root_doc` seems to do anything!

**Comment by tt4g** [comment] 2024-05-07 20:41
@jtv I have investigated `conf.py` and plugins since then, but have not found the cause.
It seems difficult to pinpoint the cause since several libraries are used for document generation.

**Comment by jtv** [comment] 2024-05-07 22:52
Well in a disturbing way I'm glad it's not just me, thanks.  If only we had better documentation...  I may have to search for examples instead of the official docs.

**Comment by tt4g** [comment] 2024-05-11 02:52
I used [the ReadTheDocs Docker image](https://dev.readthedocs.io/en/latest/design/build-images.html) to investigate what was going on.

As it turns out, prior to version 7.9, Doxygen generated documents were hosted on ReadTheDocs.
Doxygen generates XML and HTML documents in `doc/xml` and `doc/html`.
When I accessed https://libpqxx.readthedocs.io/en/7.8.1/, I saw `doc/html/index.html` generated by Doxygen.

It seems that `doc/html/index.html` was being displayed because the Doxygen generated HTML file was copied as a ReadTheBox document by `html_extra_path`.

https://github.com/jtv/libpqxx/blob/21afb0d6ec3d31424df6b7aac04c6b20c55c0a65/doc/conf.py#L135-L139

However, since version 7.9, documents generated by Sphinx from `doc/index.rst` seem to appear instead of `doc/html/index.html`.
I think the internal behavior of Sphinx has changed so that `index.html` generated from `index.rst` overwrites `doc/html/index.html` copied by `html_extra_path`.

Unfortunately, since Breathe does not seem to be able to generate the same `index.html` as Doxygen, it seems better to consider hosting Doxygen-generated documents in ReadTheDocs without using Sphinx.

**Comment by jtv** [comment] 2024-05-21 09:56
@tt4g if it works, at this point I'll gladly ditch Sphinx, ReST, and Breathe.  I don't even remember at this point why that was supposed to be so much better.  But the docs for readthedocs aren't too clear on whether you actually _need_ Sphinx.  In one place it seems to say that you do, and then in another place it seems to say that mkdocs is an alternative, and in that case there may be room to roll your own...

I've started #832 to just try again from scratch.

**Comment by jtv** [comment] 2024-05-21 11:06
Oh but there's probably a way to include existing HTML files into the Sphinx output...

**Comment by tt4g** [comment] 2024-05-21 11:34
Sphinx provides the ability to import existing HTML files by specifying `html_extra_path` in `conf.py`: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path

Previously, `index.html` generated by Doxygen took precedence over `index.html` generated by Sphinx (which is generated from `index.rst`). But now it seems that Sphinx generated `index.html` takes precedence.
I checked for other ways to import existing HTML files, but could not find one.

**Comment by jtv** [comment] 2024-05-25 14:14
OK, I am now working along the lines of "we'll pretend to use Sphinx, but really I'm just abusing its config file as a launcher for Doxygen."  It's a silly setup, but RTD [has a feature in beta](https://docs.readthedocs.io/en/stable/build-customization.html#override-the-build-process) where you can just run your own build process to generate HTML however you like.  That looks attractive, once it leaves beta.

**Comment by jtv** [comment] 2024-05-25 17:27
I've got something working with readthedocs!  \o/

It's not exactly _pretty,_ but it's functional.  Really uses only Doxygen, not Sphinx or Breathe or Exhale.  See [what I've got built for my PR](https://libpqxx--832.org.readthedocs.build/832/), while that build lasts.  (I assume it'll get cleaned up at some point, since it's for a PR.)

**Comment by tt4g** [comment] 2024-05-25 21:17
@jtv Good job! The document we have been viewing seems to have returned.

**Comment by jtv** [comment] 2024-05-26 07:58
It's a complete rewrite though, and I gave up the local documentation build.

I don't know whether anyone out there builds their own documentation for libpqxx...  Bringing it back now shouldn't be too hard.

I haven't merged this change yet.  I'll need to see about reintroducing the version string; that was the whole reason I had to pre-process the Doxyfile IIRC.

**Comment by jtv** [comment] 2024-06-05 23:42
I'm trying to bring back the local documentation build.  First in the `configure` setup.

**Comment by jtv** [comment] 2024-06-06 00:53
I think I've got it all working again, more or less.  Still a frightful amount of error output from Doxygen, and I have yet to pin the versions.  May not be so urgent though, now that I'm basically bypassing Sphinx and Breathe and all that.

**Comment by jtv** [comment] 2024-06-06 09:35
Huzzah!  I just merged a new documentation build, re-created from the ground up.  It's even pretty compatible with the old one, except...
* the resulting documentation goes into `doc/doxygen-html` (needed in order to bypass Sphinx while still using it as a "doxygen launcher" in readthedocs);
* the autotools-based build disables documentation build by default (so pass `--enable-documentation` if you want it);
* it no longer autodetects doxygen & dot (so don't enable documentation build if you don't have them installed).

**Closed** 2024-06-06 09:35 UTC
