### ISSUE TITLE
New warnings with gcc 8

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#123] opened 2018-09-17 13:54 UTC
Not sure which compilers you're using, but I've been doing some builds with gcc 8 on travis and see these:

```
PostgreSQL/pqxx/src/except.cxx:53:62: warning: ignoring attribute ‘const’ because it conflicts with attribute ‘pure’ [-Wattributes]
 PQXX_CONST const std::string &pqxx::sql_error::query() const noexcept
                                                              ^~~~~~~~
In file included from fost-postgres/Cpp/fost-pqxx/../../../PostgreSQL/pqxx/include/pqxx/except:12,
                 from PostgreSQL/pqxx/src/except.cxx:11:
fost-postgres/Cpp/fost-pqxx/../../../PostgreSQL/pqxx/include/pqxx/except.hxx:145:32: note: previous declaration here
   PQXX_PURE const std::string &query() const noexcept;   //[t56]
                                ^~~~~
PostgreSQL/pqxx/src/except.cxx:59:65: warning: ignoring attribute ‘const’ because it conflicts with attribute ‘pure’ [-Wattributes]
 PQXX_CONST const std::string &pqxx::sql_error::sqlstate() const noexcept
                                                                 ^~~~~~~~
In file included from fost-postgres/Cpp/fost-pqxx/../../../PostgreSQL/pqxx/include/pqxx/except:12,
                 from PostgreSQL/pqxx/src/except.cxx:11:
fost-postgres/Cpp/fost-pqxx/../../../PostgreSQL/pqxx/include/pqxx/except.hxx:146:32: note: previous declaration here
   PQXX_PURE const std::string &sqlstate() const noexcept;
                                ^~~~~~~~
```

**Comment by jtv** [comment] 2018-09-17 15:11
Thanks.  I'm still on g++ 7.3...  If I understand the warnings correctly,
the problem is that I used PQXX_CONST in the definitions but PQXX_PURE in
the declarations.  The really confusing part is that gcc's "const"
attribute is actually a _stronger_ assertion than the "pure" attribute.  A
function with the "const" attribute must be pure, but in addition, it can't
read any memory outside its own stack frame (my summary).


Jeroen

**Comment by jtv** [comment] 2018-09-21 11:16
I tried with gcc 8, after my patch, and no warnings now.  I'll close the issue.

**Closed by jtv** 2018-09-21 11:16 UTC
