### ISSUE TITLE
Support binary format in COPY (pqxx::stream_to)

### ISSUE THREAD

**Issue by Lamzar** [jtv/libpqxx#199] opened 2019-07-25 11:28 UTC
Class pqxx::stream_to, responsible for COPY command, works only in default text mode. There is no way to change it to binary while COPY command itself has the FORMAT option where one can change default 'text' to 'binary'.

**Comment by jtv** [comment] 2019-07-27 09:49
The problem is that we don't support binary conversions yet.  That'll be another major overhaul — not just for COPY, but for all results.

**Comment by jtv** [comment] 2019-11-09 18:18
I am actually trying to sneak some work for binary data support into libpqxx 7.  Not sure whether I'll get there — but ideas are forming and evolving.

**Comment by Laro88** [comment] 2019-12-20 10:27
stream_to with vector<char> or char* or similar be avesome, i could use it to solve #240 by going binary instead of crazy codepage & utf8 merging.

**Comment by JadeMatrix** [comment] 2019-12-21 02:20
@Laro88 you'd probably still have the same issue as #240 because I suspect that's a compiler issue.
@Lamzar @jtv I looked into the binary format when writing `stream_to`/`stream_from` but there wasn't enough documentation and iirc it changes frequently enough that text-copy is the 'supported' way.  But it's been a while.

**Comment by jtv** [comment] 2019-12-22 09:04
I agree @JadeMatrix — the information on the binary format is far too sketchy and I don't see any promise that the format will be stable.  There's a library out there though.   I'd have to make that a dependency.  So far I've been able to avoid depending on any third-party libraries, but this one might be simple enough and worth it.

**Comment by jtv** [comment] 2020-01-07 09:47
Had another look.  The library for binary transfers is libpqtypes, and it hasn't seen any updates in many years.  As things stand, I'm not going to add that dependency.

Something I think we _could_ do is: add the option to do binary transfers, but leave the entire conversion problem in the application's lap.  It would be a bit confusing in that all of the conversion machinery would be useless in that scenario, but if you absolutely want the performance and are willing to take the risk of changing or unclear binary data formats, you could get it.

We'll have to start thinking about ways to check that the binary data's format in some way matches the format which the application assumes — think "this data is the wrong size" for instance.  But libpqxx won't be able to assume actual responsibility for the match.

In the longer run, we could ask for more clarity on the binary format, and build our own conversions — preferably in C++20, which "legalises" byte swaps.  There might be a way to expose the conversion code from core postgres.

**Comment by jtv** [comment] 2020-02-09 19:14
Okay, this opens a window...  I've been working on something new where you loop over streamed query results, and they get cot onverted to native C++ types as a part of the process.  See #274.  Not merged yet, and I'm seeking feedback.

How does this tie in to binary data transfers?  It opens up the door for libpqxx to choose (in the future, not right now) which columns can be transferred as binary data and which ones we need to convert from the text format.  The calling code wouldn't notice the difference — it could be hidden underneath an API similar to the one I've got there.  Of course the library would still need to get a bit of extra information, namely the SQL types of the columns.

**Comment by jtv** [comment] 2020-03-31 15:43
I had yet another look this weekend.  What I found surprised me: yes, binary transfers are likely to be faster, but not _that much_ faster.  An integer, for instance, still seems to be transferred in a variable-width format.  So it looks like a trade-off between I/O time and CPU time, more than a clear win for one format or the other.

On top of that, libpq doesn't always let you choose formats on a column-by-column basis, so we might end up in situations where just one column in a query can't be transferred as binary, and therefore we don't get binary transfers at all.

My overall impression is that it's just not worth the portability issues, nor the complexity.  I'm not going to do binary transfers for the foreseeable future.

**Closed by jtv** 2020-03-31 15:43 UTC
