### ISSUE TITLE
vcpkg libpqxx crashes upon connection destruction

### ISSUE THREAD

**Issue by ISBachvarov21** [jtv/libpqxx#779] opened 2023-12-30 11:29 UTC
```c++
#include <iostream>
#include <pqxx/pqxx>
#include <exception>
#include <new>
#include <string>

int main()
{
    try {
        pqxx::connection c("<conn string here>");
        pqxx::work txn{ c };

        pqxx::result r = txn.exec("SELECT id, username FROM users");
        for (auto const& row : r) {
            std::cout << row[0].as<std::string>() << ' ' << row[1].as<std::string>() << std::endl;
        }

        txn.commit();
    }
    catch (std::exception const& e) {
		std::cerr << e.what() << std::endl;
		return 1;
	}

    return 0;
}
```

this apparently doesn't work
![image](https://github.com/jtv/libpqxx/assets/107104759/a9535cb6-35e7-4b30-a30e-f54dda69bdb8)

changing 
```c++
pqxx::connection c(....); 
pqxx::work txn{ c }
``` 
to 
```
pqxx::connection* c = new pqxx::connection(....); 
pqxx::work txn{ *c }
``` 
and not handling the memory via a delete or free works, but it's an obvious memory leak

any ideas?

**Comment by jtv** [comment] 2023-12-30 18:23
Something is crashing two or three libraries down from libpqxx, so it's hard to see what's going wrong.  There is no direct interaction between libpqxx and libcrypto.  It's all hidden inside libpq.

Perhaps it's related to #704, or maybe some binaries are compiled in Release mode and others in Debug mode?

**Comment by ISBachvarov21** [comment] 2023-12-30 19:49
I had the same issue with soci, so it very well may be libpq. Do you think I should report this there also? Btw, I'm using windows 11 if that helps with anything.

**Comment by ISBachvarov21** [comment] 2023-12-30 20:15
Upon further investigation, what seems to be happening is that after pqxx::connection::close() calls PQfinish on m_conn, operations are still being done on m_conn.
![image](https://github.com/jtv/libpqxx/assets/107104759/c5696cdb-12e8-49d3-8c65-90f5dad385dc)
By looking at the call stack we can see that the error is somewhere deep inside of libpq. This leads me to the conclusion that after PQfinish is called, there is either another PQfinish, or a PQ operation on m_conn, despite it being closed, which would lead to corruption of the heap. Sources for hypothesis: [very old post, possibly addressing the same crash](https://www.postgresql.org/message-id/19053.1000677182%40sss.pgh.pa.us) and [similar problem, this time on stackoverflow](https://stackoverflow.com/questions/35296988/postgres-libpq-call-pqfinish-crash)

**Comment by jtv** [comment] 2023-12-31 12:58
Thanks @ISBachvarov21 - that looks mysterious!

I thought `PQfinish()` was supposed to handle a null pointer without problems.  But looking at the libpq docs now, I see no guarantee of that!

So I think I'll have to add a check for that: `close()` can just return right away if there's no `m_conn`.  I probably didn't do that before because I like to keep the number of code paths down.

Perhaps you could try that on your system?  Add `if (!m_conn) return;` right at the top of `close()`?

**Comment by ISBachvarov21** [comment] 2023-12-31 13:03
Currently at the gym, will get back to you on the result in about 2 hours.

**Comment by jtv** [comment] 2023-12-31 13:07
Cool.  My laptop is broken so I'm not too fast myself at the moment.

Have a great new year!

**Comment by ISBachvarov21** [comment] 2023-12-31 16:41
After an intense hour of struggling to build libpqxx myself, I finally managed to do it, but returning on `!m_conn` doesn't work. I decided to check how many times it goes into `close()` by adding a simple `cout`, but it ended up being only once. That rules out the possibility of it being due to more than 1 `PQfinish()` calls on `m_conn` (unless there is another call somewhere else). In fact, it never goes into `if (!m_conn)`
![image](https://github.com/jtv/libpqxx/assets/107104759/4ae12789-0976-4a2d-b3cd-07661ec63dbf)
![image](https://github.com/jtv/libpqxx/assets/107104759/46f65f38-d7a2-4a92-bcd7-f13418c0cdb4)

**Comment by jtv** [comment] 2023-12-31 18:38
For a moment there I hoped that this might be simple.  :(

Another thing to try might be to open an SSL connection using just libpq, and seeing whether it's possible to reproduce the problem that way.

On my end, I think I'll add the check anyway just in case.

**Comment by ISBachvarov21** [comment] 2023-12-31 20:02
After thorough debugging of the problem, it seems to be stemming from `m_conn`. Code never passes the `PQfinish(m_conn)` line. Needs to be tested further to see if there's a fix. Wasn't able to find anything on libpq docs. Seems like it is an issue only on windows, and it has come about from one of the recent versions (after 7.4.1). Or it might just be an issue on libpq's side.

**Comment by jtv** [comment] 2023-12-31 20:54
So the `PQfinish()` never completed at all, even the first time!?

And I've been assuming that you've got an SSL connection - is that right?

I worry that something may be overwriting the wrong memory, but I do test against some pretty strict correctness tools.  Could it be that something else is _initialising_ the SSL/crypto libraries?  If so, you may need to inhibit that in libpqxx, so it doesn't happen twice.

**Comment by ISBachvarov21** [comment] 2024-01-02 09:55
Sorry for the late reply. I'm pretty sure I have an SSL connection, as connection to the db requires one. Been hard at the problem for the past few days. Can't find a solution for it. I don't have anything that inits the ssl/crypto libraries so that's off the question.

**Comment by jtv** [comment] 2024-01-02 14:21
I bet the problem just goes away when you connect to a database without SSL, but I don't suppose that would help us much.  :-/  If the problem still happens without SSL, at least that would tell us something.

 I don't suppose this is the same problem as #675 either, nothing from the last 3 years that I find on the Internet looks relevant...  So close to running out of ideas.

I have _some_ ideas but all ones that have already come up, and/or you've probably thought of yourself anyway:
* Debug/Release build mismatch somewhere.
* Some other build mismatch, e.g. C++17/C++20/C++23 - but libpqxx is the only C++ component here so it'd have to be between object files.
* An unusual or new cypher that's broken somehow.  Apparently that happens to some people.  Any chance you can switch cyphers just for the test?
* Yes, obviously, I worry about a bug in libpqxx but I'm just not seeing it.
* Some people have had trouble with missing libraries, or mismatched versions.
* Sometimes there's trouble when the compiler picks up the headers from one libpqxx version but the project links against a different version.  But modern libpqxx versions ensure a link failure in that case.
* _However..._  any chance you're building libpqxx as a DLL but then when you run the test programme the OS finds a different build of the DLL?
* And actually the same thing could happen with the SSL or crypto libraries.

If all else fails, we could try to reproduce the libpq calls in test code, without any libpqxx, to see whether that reproduces the problem.

**Comment by pkfox** [comment] 2024-01-04 10:38
I've run your code on Win 10 and a Debian box with no issues

**Comment by ISBachvarov21** [comment] 2024-01-05 18:14
> I bet the problem just goes away when you connect to a database without SSL, but I don't suppose that would help us much. :-/ If the problem still happens without SSL, at least that would tell us something.
> 
> I don't suppose this is the same problem as #675 either, nothing from the last 3 years that I find on the Internet looks relevant... So close to running out of ideas.
> 
> I have _some_ ideas but all ones that have already come up, and/or you've probably thought of yourself anyway:
> 
>     * Debug/Release build mismatch somewhere.
> 
>     * Some other build mismatch, e.g. C++17/C++20/C++23 - but libpqxx is the only C++ component here so it'd have to be between object files.
> 
>     * An unusual or new cypher that's broken somehow.  Apparently that happens to some people.  Any chance you can switch cyphers just for the test?
> 
>     * Yes, obviously, I worry about a bug in libpqxx but I'm just not seeing it.
> 
>     * Some people have had trouble with missing libraries, or mismatched versions.
> 
>     * Sometimes there's trouble when the compiler picks up the headers from one libpqxx version but the project links against a different version.  But modern libpqxx versions ensure a link failure in that case.
> 
>     * _However..._  any chance you're building libpqxx as a DLL but then when you run the test programme the OS finds a different build of the DLL?
> 
>     * And actually the same thing could happen with the SSL or crypto libraries.
> 
> 
> If all else fails, we could try to reproduce the libpq calls in test code, without any libpqxx, to see whether that reproduces the problem.

Tested everything that you mentioned. No success. Seeing as doing a `free()` call on `pqxx::connection` works and other people like pkfox don't have my issue I'll just settle with the `free()` solution for now. Will revisit this after my project is done, because right now I'm on a tight deadline.

**Comment by jtv** [comment] 2024-01-18 13:20
Nothing we can do but close the issue then.  :-/

**Closed** 2024-01-18 13:20 UTC

**Comment by jtv** [comment] 2024-02-10 19:45
@ISBachvarov21 one other thing that I totally forgot to mention before!  In Windows, when a DLL allocates memory, _it must be the same DLL_ that eventually frees that memory.  (Same for the executable itself.)

You can imagine how this may interact with inlining...  8-O
