### ISSUE TITLE
Release 6.2.3:  UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by zeugentor** [jtv/libpqxx#92] opened 2018-05-13 15:04 UTC
I cannot build libpqxx 6.2.3 through ./configure.

*****
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating test/unit/Makefile
config.status: creating tools/Makefile
config.status: creating win32/Makefile
config.status: creating include/Makefile
config.status: creating include/pqxx/Makefile
config.status: creating libpqxx.pc
config.status: creating pqxx-config
config.status: creating include/pqxx/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing configitems commands
Traceback (most recent call last):
  File "./tools/splitconfig", line 185, in <module>
    main()
  File "./tools/splitconfig", line 175, in main
    original_header = read_header(getcwd(), 'include/pqxx/config.h')
  File "./tools/splitconfig", line 74, in read_header
    return read_lines(os.path.join(source_tree, filename))
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)

*****
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

*****
$ python --version
Python 2.7.12

**Comment by jtv** [comment] 2018-05-17 13:45
I suppose the problem is triggered by having a non-ASCII character  in the project path?

**Comment by jtv** [comment] 2018-05-22 09:29
It's generally a bad idea to try and build in a path which non-ASCII characters, or characters with special meanings to  the shell (such as spaces, quotes, ampersands, and pipe symbols).  I'll try to improve the support for non-ASCII characters in the scripts, but there is one caveat: to your filesystem, names are not text — they're just raw bytes.  So it's technically possible for the path to contain elements that simply cannot be decoded to Unicode.

**Comment by jtv** [comment] 2018-05-23 14:13
Well, that was interesting.  I think it's fixed now.

**Closed** 2018-05-23 14:13 UTC
