### ISSUE TITLE
`query()` for prepared statements

### ISSUE THREAD

**Issue by maresc-g** [jtv/libpqxx#644] opened 2023-02-22 12:40 UTC
Hi,

We're looking to upgrade our version of pqxx in our application so I just came across the release note of the 7.7.4 in which you ask for feedback on if we still use `pqxx::result`.  
I'd like to use the feature to automatically convert types like with `query()` but we only use prepared queries so we call `exec_prepared()` which still returns a `pqxx::result`.
Is it planned to add this for prepared queries as well in future releases ?

Thanks

**Comment by jtv** [comment] 2023-02-23 09:51
Thank you for letting me know!

Sounds like it would be helpful to have an equivalent to `query` but for prepared statements.  And once we had that, the `result` class would become less relevant to you.

The `result` class is not going away, but I'd like to shift the focus of the API and documentation away from it, so that most users would never have to learn about it.  I think it will simplify the most common path for learning and using libpqxx.

**Comment by HackettJP** [comment] 2023-03-12 01:54
jtv, 

Hi, i was so my yearly refresh and noticed the comment on the pqxx::result I use it on pqxx::work exec_prepared and pqxx::work exec statements ,  alot :) 
thks
J.

**Comment by jtv** [comment] 2023-03-12 08:28
> jtv,
> 
> Hi, i was so my yearly refresh and noticed the comment on the pqxx::result I use it on pqxx::work exec_prepared and pqxx::work exec statements , alot :) thks J.

Thank you.

**Comment by alexolog** [comment] 2023-03-28 16:18
> Sounds like it would be helpful to have an equivalent to `query` but for prepared statements. And once we had that, the `result` class would become less relevant to you.

I'd like to add my vote to that.  We are using prepared statements as well, and support for prepared/parametrized queries will be much appreciated.  Until then, we are forced to use `exec`.

**Comment by jtv** [comment] 2023-03-28 17:57
OK, I'll keep it in mind as a nice project to do next.

Let's rename this ticket from "`pqxx::result` feedback" to "`query` for prepared statements" so I can keep it open and be reminded.

**Comment by alexolog** [comment] 2023-03-28 18:15
Non-prepared parameterized too please, for completeness :)

**Comment by alexolog** [comment] 2023-05-29 05:19
Bad bot!

**Comment by jtv** [comment] 2023-05-29 12:42
Indeed.  I have removed the label.

And who knows, I may find some time today to do actual work on this issue.

**Comment by alexolog** [comment] 2023-12-15 13:20
Don't know if the question is still relevant, but we're using pqxx::result quite a lot in our code.

**Comment by jtv** [comment] 2023-12-16 00:24
Thank you @alexolog .  Do you have any specific features that make `pqxx::result` useful to your use-cases than streaming queries?  Is it mainly about knowing the result size, or perhaps about random access to the rows?

**Comment by HackettJP** [comment] 2023-12-16 00:46
Hi,
Mine is a 50 stored procs of  non streamed data, "prepared statements" , into GIS data sets that return specfic data fields, validate exectution of stored procs and  with number of affected rows as well,  all to allow other programs to build up GIS datasets, "Maps" etc , alot of quries are built on the fly due to postgres enforcement of security so prepared queries is the safetst way to go.

J.

**Comment by alexolog** [comment] 2023-12-16 05:58
> Thank you @alexolog . Do you have any specific features that make `pqxx::result` useful to your use-cases than streaming queries? Is it mainly about knowing the result size, or perhaps about random access to the rows?

Knowing the result size, as well as the limitations that you documented:
> They're less flexible than SQL queries, and there's the risk of losing your connection while you're in mid-stream

**Comment by jtv** [comment] 2023-12-16 10:31
> > Thank you @alexolog . Do you have any specific features that make `pqxx::result` useful to your use-cases than streaming queries? Is it mainly about knowing the result size, or perhaps about random access to the rows?
> 
> Knowing the result size, as well as the limitations that you documented:
> > They're less flexible than SQL queries, and there's the risk of losing your connection while you're in mid-stream

Ahh right.  Thanks.  That says that there really is a place for both.

On a side note of course I should support streaming prepared statements at some point.

**Comment by jtv** [comment] 2023-12-16 10:36
> Mine is a loads stored procs of non streamed data, "prepared statements" , create GIS datasets  
> that return specfic data fields, also  validate exectution of queries, multiple progs to build up GIS dataset maps alot of dynamic queries, return summary to capture in my Transaction tables of the execution of the quries.

Thank you.  I really should support streaming of prepared statements as well...  Though they aren't necessarily great for performance (because the database can't optimise for the parameter values).


> I do also use exec as well, when i do not expect a result  DDL commands like oracle/

That makes sense - in libpqxx there's even an `exec0()` function which reports an error if the query returns any data.

**Comment by alexolog** [comment] 2023-12-16 17:25
It can be interesting to to look into the streaming.  Can you document the advantages and limitations of that approach a bit better?

For example, does it work as well (or better) for queries that return a relatively small number or rows (single, tens, hundreds)? What kinds of queries it is not suitable for? (a phrase like "may not work form *some* queries, without elaborating, does not inspire confidence). Et cetera.

**Comment by HackettJP** [comment] 2023-12-17 02:27
I pretty much use all your features :) streams as well for ingesting large data sets. into stageing tables 

The DB's application design is very much a tradtional DWH setup, ELT or ETL etc with GIS + Graphs within the datamarts, years on OWB within oracle created a similair applicance using libpqxx as its glue :) 

J.

**Comment by jtv** [comment] 2023-12-26 23:07
@alexolog In #773 I extend the documentation for streaming.  Hope that answers your questions.

**Comment by jtv** [comment] 2023-12-26 23:09
@HackettJP that's cool to hear.  I hope some day somebody will publish a library for handling PostGIS data types in libpqxx.

**Comment by jtv** [comment] 2023-12-26 23:20
> > Mine is a loads stored procs of non streamed data, "prepared statements" , create GIS datasets
> > that return specfic data fields, also  validate exectution of queries, multiple progs to build up GIS dataset maps alot of dynamic queries, return summary to capture in my Transaction tables of the execution of the quries.
> 
> Thank you. I really should support streaming of prepared statements as well... Though they aren't necessarily great for performance (because the database can't optimise for the parameter values).

On second thoughts I'm not so sure that streaming prepared statements makes a lot of sense!  The purpose of prepared statements is to reduce the overhead of parsing and planning a query.  That overhead is usually tiny.  A prepared query's actual run time is normally equal or worse to that of just executing the query _ad hoc._  So prepared queries make sense when the query planning cost is greater than the data handling cost: the query is complex but does not return a lot of data.

Streaming optimises in exactly the opposite direction.  It increases the query's startup overhead, but speeds up data handling at scale.  So it shines when the overwhelming cost is in data handling.

I'd wait for evidence that it's worthwhile before supporting a tradeoff where you save on planning overhead but add probably much greater streaming overhead, and then speed up large data transfers but risk slowing down execution.

**Comment by jtv** [comment] 2024-06-30 14:01
It's getting a little awkward making up all these different names for very similar functions.  What if we had a marker type for prepared functions, and that would be the only difference between executing a prepared statement (where you pass the statement's name) and executing a regular statement (where you pass the SQL statement itself)?

Thinking of something like `auto data = tx.exec(pqxx::prepared{"list_users"});`

That would perhaps make it a bit easier to add prepared-statement versions of `exec0()`, `exec1()`, `query()`, `stream()`, and so on.

**Comment by LucidApparition** [comment] 2024-07-12 15:08
Hello, I am new to `libpqxx/pqxx` and have hit a wall with executing a prepared query. This thread seemed to be the only relevant one I could find.

I am trying to check if a product ID exists in my table. When I run exec_prepared with the prepared query and parameter, it seems to crash. However, it runs fine if not given a placeholder.


```
cout << "Preparing statement." << endl;
C.prepare("check_product_id", "SELECT 1 FROM product_runs WHERE product_id = $1");
C.prepare("given_product_id", "SELECT 1 FROM product_runs WHERE product_id = 2024071101");

cout << "Running exec_prepared to check product_id: " << product_id << endl;

pqxx::result given_result = W.exec_prepared("given_product_id");
cout << "Given result: " << given_result.empty() << endl;

pqxx::result check_result = W.exec_prepared("check_product_id", product_id);
cout << "Check result: " << check_result.empty() << endl;
```
#### Terminal output:

```
Preparing statement.
Running exec_prepared to check product_id: 2024071101
Given result: 1
```

I'm not sure what is causing it to just stop.
Any feedback is helpful. 
Thank you.

**Comment by tt4g** [comment] 2024-07-12 21:20
@LucidApparition If the exception is `throw` inside pqxx, you can use `try`-`catch` to handle the exception, and you should be able to determine the cause from the exception message.

**Comment by jtv** [comment] 2024-07-12 21:34
Strange...  What's the type of the variable you're passing as the parameter?

**Comment by HackettJP** [comment] 2024-07-12 22:47
something like this to think about , code_page or unicode stuff as well.

you may need to convert the variable or c.str() it.
std::string product_id = pqxx::to_string(given_product_id_incoming);  

a good approach to the query logs on postgresql backend logs  check to see if it matchs up to what you sent, be mindfall and check if their any single quotes  '    '     or double quotes 

failing that is use the quote or escape depending etc..to see what you actualy sent in c++ land

worker.exec(](std::cout <<)""" fooo barrr """+worker.quote(startDate)+""" foo barr ;  """  << std::endl; 
or with table names
"""+worker.esc(targettempTable)+"""
std::cout << """ UPDATE """+worker.esc(targetfinaltable)+""" fooor barr "") << std::endl; 

pqxx::result response {};
       
try { 
....
C.prepare("check_product_id", "SELECT 1 FROM product_runs WHERE product_id = $1"); response= W.exec_prepared("given_product_id");
.....
.....
worker.commit();
..
        catch (const pqxx::sql_error &e)
        {
            std::cerr << e.what() << std::endl;
           worker.abort();
            exit(1);

        }

**Comment by LucidApparition** [comment] 2024-07-13 15:55
@tt4g @jtv @HackettJP 

Sorry about not providing that information.
The code is in a try/catch and didn't catch anything.
The product ID is an int
And I ran it in debug mode and got this:

```
Exception thrown at 0x00007FFCC5BFFABC in AlliumCS.exe: Microsoft C++ exception: std::length_error at memory location 0x000000DB1378E8E0.
Exception thrown at 0x00007FFD54540003 in AlliumCS.exe: 0xC0000005: Access violation executing location 0x00007FFD5454003.
```

I believe this is just saying there is a pointer issue but unsure of how to fix it.

#### Here is the full code block of my function up to the issue:

```
// Function to check which faces have no value at product_id
vector<string> checkFaces(pqxx::connection &C, int product_id, int numSensors)
{
    vector<string> faces = {"top", "right", "bottom", "left"};
    vector<string> faces_with_no_value;

    try
    {
        // Begin a transaction
        pqxx::work W(C);

        cout << "Checking Faces..." << endl;
        lock_guard<mutex> guard(mtx); // Lock the mutex

        // Check if the product_id exists in the table using prepared statement
        C.prepare("check_productID", "SELECT 1 FROM product_runs WHERE product_id = $1");

        auto result_exists = W.exec_params("check_productID", product_id);
        int check_value = result_exists.empty() ? 0 : 1;
        cout << "Product ID exists: " << check_value << endl;

```

**Comment by tt4g** [comment] 2024-07-13 21:23
I can't tell where the problem is from just the code you provided, but there are a few things I'm curious about.

1. there is a breaking change in `std::mutex` and it crashes unless using Visual Studio Code runtime version 17.10.0 or later (microsoft/STL#4730), can you avoid using mutex?
2. you are using `using namespace std;`, but this can break the behavior of the library, so please try not to use it.

**Comment by LucidApparition** [comment] 2024-07-15 14:22
@tt4g I removed the mutex and namespace. And now only have this error regarding memory access. 
```
Unhandled exception at 0x00007FFD01381043 in AlliumCS.exe: 0xC0000005: Access violation executing location 0x00007FFD01381043.
```

I also tested the data type to be sure and passed it as a string. Which allowed the program to continue through. 
```
Starting program...
Starting measurement...
Device opened...
Measuring...
Reading Data...
Checking Faces...
Product ID: 2024071201
numSensors: 2
Checking if product ID exists..
Error checking faces with no value: bad array new length
Failed to insert/update attributes: bad array new length
Timestamp: Mon Jul 15 10:14:19 2024, Current Values: -1.745 -1.745 , Current Statuses: running running
Product runs updated successfully.
```
Yielding a different output but essentially the same problem.

This is my table for reference
```
CREATE TABLE product_runs(
    product_id integer NOT NULL,
    ...
    PRIMARY KEY(product_id)
```

The question I am having now, is, is it a problem with how I have my code structured or a problem with the libraries?

**Comment by tt4g** [comment] 2024-07-15 20:56
The code provided does not appear to have any problems with the use of the library.
Try commenting out the code a bit as you did with the two pieces of code and look for the cause of the crash.

**Comment by LucidApparition** [comment] 2024-07-16 10:02
@tt4g As far as isolation goes, I have isolated it to being that one line of code not functioning with the parameter.
```
auto result = W.exec_params("SELECT 1 FROM product_runs WHERE product_id = $1", product_id);
```

I ran a test by bringing everything into my main script so that I wasn't passing any variables through functions or the connection string.
#### Entire main.cpp:
```
// PM-512 Main Function Entry Point
#include "measurementControl.h"
#include "dataProcessing.h"
#include <iostream>
#include <chrono>
#include <thread>
#include <pqxx/pqxx>
#include <sstream>

int main()
{
    std::cout << "Starting program..." << std::endl;

    // Set variables
    char *dbname, *dbuser, *dbpassword, *dbhostaddr, *dbport;

    // Check and retrieve environment variables
    if (_dupenv_s(&dbname, nullptr, "DB_NAME") != 0 ||
        _dupenv_s(&dbuser, nullptr, "DB_USER") != 0 ||
        _dupenv_s(&dbpassword, nullptr, "DB_PASSWORD") != 0 ||
        _dupenv_s(&dbhostaddr, nullptr, "DB_HOSTADDR") != 0 ||
        _dupenv_s(&dbport, nullptr, "DB_PORT") != 0)
    {
        std::cerr << "Error: One or more environment variables are not set." << std::endl;
        return 1;
    }

    // Create connection string using std::stringstream
    std::stringstream ss;
    ss << "dbname=" << dbname
       << " user=" << dbuser
       << " password=" << dbpassword
       << " hostaddr=" << dbhostaddr
       << " port=" << dbport;
    std::string conn_str = ss.str();

    // Set user inputed variables
    int product_id = 2024071601;
    double length = 152.4;
    std::string direction = "north";
    int numSensors = 2;

    try
    {
        pqxx::connection C(conn_str);
        if (!C.is_open())
        {
            std::cerr << "Failed to open database." << std::endl;
        }
        pqxx::work W(C);

        std::cout << "Testing query in Main..." << std::endl;

        std::cout << "Selecting from billet_attributes with hardcoded length..." << std::endl;
        auto attribute1 = W.exec_params("SELECT * FROM billet_attributes WHERE length = 152.4");
        std::cout << "Query passed with no error. Result size: " << attribute1.size() << std::endl;

        std::cout << "Selecting from product runs with hardcoded product id..." << std::endl;
        auto product1 = W.exec_params("SELECT 1 FROM product_runs WHERE product_id = 2024071601");
        std::cout << "Query passed with no error. Result size: " << product1.size() << std::endl;

        std::cout << "Selecting from billet_attributes with param length..." << std::endl;
        auto attribute2 = W.exec_params("SELECT * FROM billet_attributes WHERE length = $1", length);
        std::cout << "Query passed with no error. Result size: " << attribute2.size() << std::endl;

        std::cout << "Selecting from product runs with param product id..." << std::endl;
        auto product2 = W.exec_params("SELECT 1 FROM product_runs WHERE product_id = $1", product_id);
        std::cout << "Query passed with no error. Result size: " << product2.size() << std::endl;

        W.commit();
    }
    catch (const std::exception &e)
    {
        std::cerr << "Exception: " << e.what() << std::endl;
    }

    // Free allocated memory for environment variables
    free(dbname);
    free(dbuser);
    free(dbpassword);
    free(dbhostaddr);
    free(dbport);

    std::cout << "Program finished." << std::endl;
    return 0;
}
```
#### Terminal Output:
```
Starting program...                                                                                                 
Testing query in Main...
Selecting from billet_attributes with hardcoded length...
Query passed with no error. Result size: 11
Selecting from product runs with hardcoded product id...
Query passed with no error. Result size: 0
Selecting from billet_attributes with param length...
```
And it still crashes at the first line with a parameter.
```
public:
    _CONSTEXPR20 void reserve(_CRT_GUARDOVERFLOW size_type _Newcapacity) {
        // increase capacity to _Newcapacity (without geometric growth), provide strong guarantee
        if (_Newcapacity > capacity()) { // something to do (reserve() never shrinks)
            if (_Newcapacity > max_size()) {
                _Xlength();
            }

            _Reallocate<_Reallocation_policy::_At_least>(_Newcapacity);
        }
    }

Exception has occurred: W32/0xC0000005
Unhandled exception at 0x00007FF9FD508348 in AlliumCS.exe: 0xC0000005: Access violation executing location 0x00007FF9FD508348.
```

**Comment by tt4g** [comment] 2024-07-16 10:32
That is very strange. What version of libpqxx are you using? Also, did you build it yourself?

---

By the way, did the following code show the crashed code?
It does not appear to be libpqxx source code.

> public:
>     _CONSTEXPR20 void reserve(_CRT_GUARDOVERFLOW size_type _Newcapacity) {
>         // increase capacity to _Newcapacity (without geometric growth), provide strong guarantee
>         if (_Newcapacity > capacity()) { // something to do (reserve() never shrinks)
>             if (_Newcapacity > max_size()) {
>                 _Xlength();
>             }
> 
>             _Reallocate<_Reallocation_policy::_At_least>(_Newcapacity);
>         }
>     }

**Comment by tt4g** [comment] 2024-07-16 10:47
@LucidApparition This is the `std::vector` source code: https://github.com/microsoft/STL/blob/ecbc1efa09936f4ef5af529e770a95a29a4290d3/stl/inc/vector#L1680-L1690
If there is an access violation in that code, it is a bug in MSVC.

**Comment by LucidApparition** [comment] 2024-07-16 10:59
Ok, thank you @tt4g I'll look into that.

**Comment by tt4g** [comment] 2024-07-16 11:34
@LucidApparition I searched the MSVC STL repository, but could not find any defects that match this case.
However, it is possible that it is a bug in the MSVC, so try updating the MSVC and see if the problem recurs.

**Comment by LucidApparition** [comment] 2024-07-16 11:44
@tt4g Yes, I am currently updating my libraries and paths.

**Comment by LucidApparition** [comment] 2024-07-16 13:27
@tt4g After updating everything, nothing has changed.
I did tested a few different use cases for querying.

Using a query string, exec1, and exec0 seemed to work with passing the parameter.
However, using a C.prepare with exec_prepared and exec_params both crashed. 

```
std::cout << "Using raw SQL..." << std::endl;
std::string query = "SELECT 1 FROM product_runs WHERE product_id = " + W.quote(product_id);
auto rawSQL = W.exec(query);
std::cout << "Query passed with no error. Result size: " << rawSQL.size() << std::endl;       

Output:
Using raw SQL...
Query passed with no error. Result size: 0
```
```
std::cout << "Using exec1..." << std::endl;
W.exec1("SELECT 1 FROM product_runs WHERE product_id = " + W.quote(product_id));
std::cout << "Query passed with no error on exec1 " << std::endl;

Output:
Using exec1...
Exception: Expected 1 row(s) of data from query , got 0.
```
```
std::cout << "Using exec0..." << std::endl;
W.exec0("SELECT 1 FROM product_runs WHERE product_id = " + W.quote(product_id));
std::cout << "Query passed with no error on exec0 " << std::endl;

Output:
Using exec0...
Query passed with no error on exec0
```
```
C.prepare("check_product_id", "SELECT 1 FROM product_runs WHERE product_id = $1");
std::cout << "Using prepared..." << std::endl;
auto prepared = W.exec_prepared("check_product_id", product_id);
std::cout << "Query passed with no error. Result size: " << prepared.size() << std::endl;

Output:
Using prepared...
```
```
std::cout << "Using exec_params..." << std::endl;
auto execp = W.exec_params("SELECT 1 FROM product_runs WHERE product_id = $1", product_id);
std::cout << "Query passed with no error. Result size: " << execp.size() << std::endl;

Output:
Using exec_params...
```

**Comment by tt4g** [comment] 2024-07-16 13:42
@LucidApparition Very strange, `exec_params()` has been confirmed to work in several tests.

https://github.com/jtv/libpqxx/blob/30d41bcdfa46aa278b034eb82aa078dcb671ce0e/test/unit/test_stream_from.cxx#L206-L237

https://github.com/jtv/libpqxx/blob/30d41bcdfa46aa278b034eb82aa078dcb671ce0e/test/unit/test_transaction_focus.cxx#L40-L49

However, I could not find any pattern in the test cases where `double` is passed as a parameter.
Maybe there is a problem only when passing `double`.
If you change the type of `product_id` to `std::string` instead of `double`, does the problem still occur?
If not, you may want to open a new issue to manage this problem.

**Comment by LucidApparition** [comment] 2024-07-16 13:51
@tt4g product_id is an int, my length variable is a double. I used that to see if it was an int issue or not. 
product_id is an int in the db but using the direction, which is a varchar(10), I get an exception.
```
int product_id = 2024071601;
double length = 152.4;
std::string direction = "North";
int numSensors = 2;
```
```
std::cout << "Using exec_params..." << std::endl;
auto execp = W.exec_params("SELECT 1 FROM billet_attributes WHERE top_direction = $1", direction);
std::cout << "Query passed with no error. Result size: " << execp.size() << std::endl;

Output:
Using exec_params...
Exception: bad array new length
Program finished.
```

**Comment by tt4g** [comment] 2024-07-16 14:06
@LucidApparition This error looks like a `std::bad_array_new_length` message in MSVC STL.

https://github.com/microsoft/STL/blob/ecbc1efa09936f4ef5af529e770a95a29a4290d3/stl/inc/exception#L159-L162

It is strange that this error occurs.
I am guessing that your application is doing some undefined behavior.
Where did you get the libpqxx library you are using?

**Comment by KayEss** [comment] 2024-07-16 14:41
Just a couple of notes on your design:

* Use of `double` and doing a equality check is liable to be unreliable due to variances caused by floating point calculations. This makes them a poor choice for a primary key. Whether this is actually going to be a problem for you depends entirely on how these numbers are parsed and processed. Don't be surprised if you can't retrieve data you know to be in the database.
* You use `int` with numbers like 2024071601 is very close to the limit on a 32 bit signed int. Any variance here is likely to lead to an overflow which is UB. Whether this is going to be a problem depends entirely on what other values you're trying to use. This specific one you use here is fine, but you can't add another digit to the `01` you use after the date portion.

The bug you're trying to track down does look a lot like the sort of problem caused by mixing debug & release builds. Can you check that vcpkg does produce both a release and a debug version of the library, and you're linking against the correct one? In any case, can you try to see if the behaviour changes based on whether you're doing a debug or a release build of your code?

**Comment by LucidApparition** [comment] 2024-07-16 15:16
@KayEss Thank you, very helpful. The product_id which is an int, atm, is the primary key not the double. To avoid any issues in the future, would you recommend changing it to a varchar?
For the mixing builds, I was only creating one Debug build and not both a Debug and Release because of the issues.
 
For my commands I'm using
```
cmake .. -G "Visual Studio 17 2022"

msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform=x64 /p:VcpkgEnableManifest=true /p:PlatformToolset=ClangCL /p:ClCompile_AdditionalOptions="/fsanitize=address" "AlliumCS.vcxproj"
```

**Comment by KayEss** [comment] 2024-07-16 15:18
I see you're using clang-cl. I don't know if that has full binary compatibility with MSVC. So you should check that the vcpkg build and your build:

* use the same compiler
* use the same stdlib
* use the same debug or release

**Comment by KayEss** [comment] 2024-07-16 15:22
As you're using cmake, the simplest way to make sure everything is correct is to use `add_subdirectory` to include the libpqxx build. That way cmake sets all the build parameters and they're always correctly in sync

**Comment by LucidApparition** [comment] 2024-07-16 18:18
@KayEss It looks like you were right on the issue being with the build. 
After deleting and rebuilding my build file, vcpkg, and cmaketext It looked like there was an issue with reading the libpqxx.lib file, finding the correct triplet, and possibly some other issues overall causing exec_params and other functions of pqxx to not work.

My issue has been solved in regards to using exec_params and exec_prepared.

**Comment by jtv** [comment] 2024-07-20 15:14
Thanks all!  I was on a more or less forced vacation for the past two weeks, so I'm most grateful to find this resolved.  I would not have been much use on this one.

I do sometimes wish C++ compilers would drop the pretense that binaries are link-compatible when they really aren't...

**Comment by jtv** [comment] 2024-07-28 09:35
I suppose we can close the ticket then.

**Comment by jtv** [comment] 2024-07-28 10:26
This ticket unfortunately got "hijacked" for a unrelated problem, and the original request got downed out.

So I'll close this one, and file a fresh one for the original issue.  @LucidApparition in future please file a new ticket when no existing ticket exactly matches your problem.

**Comment by jtv** [comment] 2024-07-28 10:34
The new ticket for the original question is #871.

**Closed** 2024-07-28 10:35 UTC
