### ISSUE TITLE
Bad exception sql_error in place of broken_connection?

### ISSUE THREAD

**Issue by xamix** [jtv/libpqxx#280] opened 2020-02-21 08:28 UTC
Hello,

I'm using Ubuntu x64 in 18.04
Libpqxx **7.0.1**
Libpq version **12.0.1**

Here is my test case:
I'm opening a connection to my PG server with the field `tcp_user_timeout` at 10000 (10 seconds).
Everything is good here. 
Then I unplug my Ethernet cable and do an insert in database (with a work object on my connection)
It stall for about 10 seconds (the amount of the value of `tcp_user_timeout`) and then an `pqxx::sql_error` exception is throwed with the message equal to `Connection timed out`.

In the [libpq documentation](https://www.postgresql.org/docs/current/libpq-connect.html) it is noted that the connection is forcibly closed when this arrive:

> tcp_user_timeout
> Controls the number of milliseconds that transmitted data may remain unacknowledged before a connection is **forcibly closed**. A value of zero uses the system default. This parameter is ignored for connections made via a Unix-domain socket. It is only supported on systems where TCP_USER_TIMEOUT is available; on other systems, it has no effect.

So I was expecting to get a `pqxx::broken_connection` but it is not the case.
I only get `pqxx::broken_connection` when I connect to database but not after.

Also I checked the connection function `is_open()` when this arrive, and it return true when Timeout occur.
Is there a solution to get a  `pqxx::broken_connection` when server is not reachable for my example in 10s when doing a request?

Regards

**Comment by jtv** [comment] 2020-02-21 09:53
That's a good question...  When you call `is_open()`, it calls libpq.  So evidently libpq is still saying that the connection is open!

Do you happen to know what the exception's `sqlstate()` returns?  I'm guessing it's not one of the codes that start with "08", or you'd get a `broken_connection`.  And what happens if you try to continue using the connection after the error?

**Comment by xamix** [comment] 2020-02-21 10:17
> Do you happen to know what the exception's sqlstate() returns?

The `sqlstate()` function return an empty string.
The `what()` return `could not receive data from server: Connection timed out`

> And what happens if you try to continue using the connection after the error?

A `pqxx::failure` exception is thrown with the `what()` function returning `Could not obtain client encoding.`

**Comment by xamix** [comment] 2020-02-21 11:25
Some more details: 
The underlying `socket` seem always valid since the connection function `sock()` return socket value > 0.

Using Linux function `getsockopt` to get `SO_ERROR` code on socket return 0.
So no error on socket, maybe cleaned by libpq when "catching" the timeout exception.

So for now I'm stuck to detect that the request failed because of a timeout!
And so I'm not able to know that I need to reconnect after this event and try again to send my request!

**Comment by jtv** [comment] 2020-02-22 08:14
I think I have it!  The error you got was "Could not obtain client encoding."  That means we **did not get an error from `PQexec`, but from `PQclientEncoding`.**

`PQclientEncoding` does not return any details when it fails.  It just returns -1, and so libpqxx throws a `pqxx::failure`.

What it should do instead is: check if the connection is still good, and if not, throw a `broken_connection`.  I'll get right on it.

**Comment by jtv** [comment] 2020-02-22 08:17
Actually the implications are much more far-reaching.  :(  It also means that obtaining a connection's client encoding should not be `const`.

**Comment by jtv** [comment] 2020-02-22 08:29
I was wrong.  I thought that the error meant that `PQclientEncoding` queries the database.  But it does not.  It just _checks_ whether the connection is still OK, and that happens before libpqxx checks whether the connection is still OK.  So no far-reaching implications.

**Comment by xamix** [comment] 2020-02-22 08:49
Yes...

I come with the `errno` solution because I have found no solution to check that the connection is still in a good state.

There are no error on socket as I have said before.
It seem the socket is good until you use it to send or receive again! An error is then thrown.
In fact I think that when the call to `exec` timeout, the caller should be aware of this error and allow you to throw a broken connection. And at least the PQStatus should return a Bad connection because it seem the connection is not usable anymore after that...

**Comment by jtv** [comment] 2020-02-22 09:11
I hope that fix I just pushed will solve the problem.  Could you verify?

The `errno` fix is probably too dangerous because lots of standard library functions will overwrite `errno` even when they're successful.

The timeout in that comment (about returning 0) looks to me like a wait timeout on the client, not really related to a server-side timeout.  But I could be wrong.

**Comment by xamix** [comment] 2020-02-22 09:32
`errno` is indeed not a good solution but as it is thread local and in my use case, only your library is used and is calling libpq underlying then I use that....

I cannot test your patch until Monday. But as I understand it will only throw when use again connection, not when the timeout occur and fire the `pqxx::sql_error`

**Comment by jtv** [comment] 2020-02-22 09:44
Well I found that nowadays, the code that checks for an error and throws an exception, _first_ checks the encoding.  And that fails if the connection is bad!

I'm looking into rewriting the whole way I check for errors, but that's going to be more work.

**Comment by xamix** [comment] 2020-02-22 10:13
But one thing seem strange to me (I have no access to my environment for now, so just remember):

I checked the result of `is_open()` (which in the end call `PQstatus` function) right after the timeout and it returned **True**.
The function `PQclientEncoding` check state in the same maner of `PQstatus`, by checking the underlying `conn` and `conn->status`.

So which call changed the state of `is_open()` to **False**?
I was thinking that there was no way to check that connection was closed until doing a network call which will fail?

**Comment by jtv** [comment] 2020-02-22 15:38
Yeah, I can't say I really understand it either.  Generally, yes, something has to fail before libpq can mark the connection as broken.  There used to be a lot of retry code in both libpq and libpqxx that might have reset the connection, but I think libpq ended up believing the OS when it says there's an error — and I similarly removed all that complexity from libpqxx.

**Comment by xamix** [comment] 2020-02-24 09:41
Just tested your patch:

1) On timeout the error throwed is `pqxx::sql_error`:
The `sqlstate()` function return an empty string.
The `what()` return `could not receive data from server: Connection timed out`

2) If I try to continue using the connection after the error, now a `pqxx::broken_connection` is thrown.

To conclude, the **2)** Is now good but the **1)** should have throwed also a `pqxx::broken_connection` at first place since the connection is broken when it timeout and not usable anymore.

Anyway what you have fixed works here :-)

**Comment by jtv** [comment] 2020-02-24 11:50
Okay, found another spot that needed a check for a broken connection.  It's that nasty scenario where we get no result _at all_ and so there's no way for libpq to tell us what the problem was.

@xamix Could you re-test the current master?

**Comment by xamix** [comment] 2020-02-24 13:43
Re-tested the last master and same behavior than your last patch.

**Comment by jtv** [comment] 2020-02-25 09:57
Something that makes it extra annoying is that I've only got postgres 10 on my laptop.  If I had postgres 12 at hand, I _think_ this would be a simple way to reproduce the problem:

    #include <iostream>
    #include <pqxx/pqxx>

    int main()
    {
      pqxx::connection cx{"host=localhost tcp_user_timeout=1"};
      pqxx::work tx{cx};
      tx.exec0("SELECT pg_sleep(3)");
      std::cout << cx.is_open() << '\n';
    }

**Comment by xamix** [comment] 2020-02-25 12:25
I have also postgres server at **10.11**.

Testing your code with
Libpqxx **7.0.(3)**
Libpq version **12.0.1**

Executing your code throw  `pqxx::unexpected_rows` after the 3 seconds timeout.
Itested with other greater `timeout `and other greater `tcp_user_timeout`, it seem that `tcp_user_timeout` have no effect here...

**Comment by jtv** [comment] 2020-02-25 19:13
I thought `tcp_user_timeout` was new in postgres 12..?

**Comment by jtv** [comment] 2020-02-25 19:14
(And yes, it turns out I shouldn't have used `tx.exec0()` for `pg_sleep` because it does return a row...)

**Comment by xamix** [comment] 2020-02-25 19:20
I was thinking that `tcp_user_timeout` is on client side settled on client socket?
It seem that it works like that in my currrent setup

**Comment by jtv** [comment] 2020-02-25 19:59
Ah, I thought you were trying it with the postgres 10 _client._  I don't have either on my laptop.

**Comment by xamix** [comment] 2020-02-25 20:56
```
The TCP user timeout controls how long transmitted data may remain unacknowledged before a connection is forcefully closed. It is a local, per-connection parameter. This document specifies a new TCP option - the TCP User Timeout Option - that allows one end of a TCP connection to advertise its current user timeout value
```

This explain why on your test case it do not timeout.

It's not related with Postgres, but with TCP connection. On your test, TCP communication is good and we receive acknowledgment of the command (on TCP layer).
At the same time the request is always executing...

**Comment by jtv** [comment] 2020-03-03 23:30
@xamix I found that I could clean up the error-checking code without breaking the ABI.  The current `master` makes it all a bit simpler, so it may resolve some of your problems.

**Comment by xamix** [comment] 2020-03-04 09:50
I tested the last master and nothing seem change (the first exception is always a `pqxx::sql_error`:

On first timeout:
`pqxx::sql_error` with what()= `could not receive data from server: Connection timed out`

If I continue to use the connection:
`pqxx::broken_connection` with what()= `Lost connection to the database server.`

**Comment by jtv** [comment] 2020-03-05 18:16
Then I despair about solving this one at this stage...  It does sound like a libpq bug, and it should probably be fixed there.  :/

**Comment by jtv** [comment] 2020-03-08 21:17
I just built my own postgres 12 in order to reproduce the problem, but of course I can't break the connection to my _local_ database server.  :(

This piece of code should reproduce the problem at the C/libpq level:

    #include <cassert>
    #include <iostream>
    include <postgresql/libpq-fe.h>

    int main(int, char *argv[])
    {
      assert(argv[1] != nullptr);
      std::string host_and_port{argv[1]};
      auto connstr{"postgresql://" + host_and_port + "&tcp_user_timeout=1"};
      auto conn{PQconnectdb(connstr.c_str())};
      if (PQstatus(conn) != CONNECTION_OK)
      {
        std::cerr << PQerrorMessage(conn);
        return 1;
      }
      std::cout << "Unplug network cable within one minute.\n";
      auto res{PQexec(conn, "SELECT pg_sleep(60)")};
      std::cout << "result status: " << PQresStatus(PQresultStatus(res)) << '\n';
      if (PQstatus(conn) == CONNECTION_OK)
        std::cout << "Connection is OK.\n";
      else
        std::cout << PQerrorMessage(conn) << '\n';
    }

If we could run this and reproduce the problem, it'd at least tell us whether the problem is in libpq or in libpqxx.

**Comment by KayEss** [comment] 2020-03-09 02:20
> but of course I can't break the connection to my _local_ database server

I expect `killall -9 postgres` would be quite effective :-)

**Comment by xamix** [comment] 2020-03-09 06:09
@jtv If you would like to reproduce the "issue" I tested, it's not the postgresql version which matter, but only the libpq since the `tcp_user_timeout` only play on client socket:

```
The TCP user timeout controls how long
transmitted data may remain unacknowledged
before a connection is forcefully closed.
It is a local, per-connection parameter.
```
The timeout occur on socket and hence your test can be changed to put a sleep between the two following line in order to let you time to unplug the Ethernet cable:

```
std::cout << "Unplug network cable within 10seconds and let the next call occur while Ethernet cable is unplugged.\n";
// Put a sleep here to let you time to unplug the Ethernet cable and let execute subsequent call which will timeout
std::this_thread::sleep_for(std::chrono::seconds(10));
auto res{PQexec(conn, "SELECT pg_sleep(60)")};
```

**Comment by jtv** [comment] 2020-03-09 15:48
@KayEss I figured killing the postgres daemon on a local connection would simply terminate the TCP connection, and the client would notice immediately.  I need the client to wait until the timeout.  Perhaps I could add a temporary firewall rule to block the packets.

@xamix yes, I understand...  I may set up a remote database server later but it takes a bit of preparation.

**Comment by kimi20071025** [comment] 2020-05-14 02:03
Before the problem solved perfectly, it there any another solution? How about belows:
1. Every time after executing sql, the application releases the connection. And try to reconnect PG when using it next time.
2. If find the exception, application try to reconnect PG.

**Comment by tt4g** [comment] 2020-05-14 02:57
> 1. Every time after executing sql, the application releases the connection. And try to reconnect PG when using it next time.
> 2. If find the exception, application try to reconnect PG.

IMO:

I recommend that users write code that catches the exception themselves and reconnects to the PostgreSQL server.
This is because the automatic reconnect configuration in the library can cause very confusing problems.

Consider a scenario in which an exception is raised during the execution of a nested transaction and a reconnect is made inside the library.
The user will continue to issue SQL statements unknowingly, even if a reconnection occurs during the execution of a nested transaction.
Reconnected connections may have to wait for the transaction that the previous connection was performing to time out. In the worst case, inconsistent data will be committed on the new connection.

I believe that the fact that a connection has been disconnected should be communicated to the user code.

**Comment by jtv** [comment] 2020-05-14 07:05
@kimi20071025 that would make everything _massively_ slower!

**Comment by jtv** [comment] 2020-06-03 21:38
@xamix I just had another look at this old bug.  I hate doing it, but I started treating an empty or missing SQLSTATE as meaning that the connection is broken.  Hopefully this will at least fix this problem.

**Comment by xamix** [comment] 2020-06-04 08:00
Ho okay!
Yes to me it also seem to be a hack, hoping no true SQL error will be reported without SQLSTATE...

Anyway thinking to it, if no error are "filled", it's probably that the server didn't respond with an error and so that the connection is in a bad state.

I will try your master branch, if it works I will probably switch to it since it will make my code a lot cleaner!

**Comment by xamix** [comment] 2020-06-05 07:51
@jtv It seem your patch is working for me!
It fire the `broken_connection` at the right time.

**Comment by jtv** [comment] 2020-06-14 01:51
Thanks for your help with this!  Closing the ticket now.

**Closed by jtv** 2020-06-14 01:51 UTC
