### ISSUE TITLE
Poor performance of populating data in database by insert command

### ISSUE THREAD

**Issue by MaximNM** [jtv/libpqxx#163] opened 2019-02-19 21:08 UTC
Hello,

I'm trying to insert about 1.5M rows in simple DB without any constrains and triggers.
If client and server are located on same machine it's fast around 4 minutes.
If they are located on different machines but in one LAN it's take around 20 minutes :(
I really don't understand where is the bottleneck.

Please see below my code may be you'll find a mistake.
```
 try {
        // Connection
        std::string conn_string{"host= dbname= user= password="};
        
        // Create connection
        pqxx::connection conn(conn_string);
        
        // SQL statement preparation
        // to_timestamp($3) for time in timestamp
        conn.prepare("insert-ESTOHLCV", "insert into historicalmin_test (id, exchangeid, symbolid, time, open, high, low, close, volume) values (0, $1, $2, $3, $4, $5, $6, $7, $8::float8::numeric::money)");
        
        // Select from DB
        pqxx::nontransaction ntxn(conn, "select");
        ntxn.exec0("truncate table historicalmin_test");

        int exchid = 2;
        int symbid = 1;
        
        // extract(epoch from time) as time // for time in timestamp
        pqxx::result res = ntxn.exec_params("select time, open ::money::numeric, high ::money::numeric, low ::money::numeric, close ::money::numeric, volume ::money::numeric from historicalmin where exchangeid = $1 and symbolid = $2", exchid, symbid);
        if (!res.size()) {
            std::cerr << "Empty result set\n";
            return 1;
        }
        
        std::vector<tohlcv> tohlcvs;
        
        for (const auto& r: res) {
            struct tohlcv s;
            //std::cout << r["time"] << '|' << r["open"] << '|' << r["high"] << '|' << '|' << r["low"] << '|' << r["close"] << '|' << r["volume"] << '|' << std::endl;
            std::istringstream in{r["time"].as<std::string>()}; in >> parse("%F %T%z", s.time);
            //s.time = floor<minutes>(sys_seconds{seconds(r["time"].as<int>())});
            s.open = r["open"].as<float>();
            s.high = r["high"].as<float>();
            s.low = r["low"].as<float>();
            s.close = r["close"].as<float>();
            s.volume = r["volume"].as<float>();
            tohlcvs.push_back(s);
            //std::cout << exchid << '|' << symbid << '|' << make_zoned(current_zone(), floor<minutes>(s.time)) \
            << '|' << s.open << '|' << '|' << s.high << '|' << '|' << s.low << '|' << s.close << '|' << s.volume << '|' << std::endl;
        }
        ntxn.commit();
        
        std::cout << "Got total TOHLCVs: " << tohlcvs.size() << std::endl;
        
        std::cout << "Starting inserting in DB: " << make_zoned(current_zone(), std::chrono::system_clock::now()) << std::endl;
        
        // Store the tohlcvs to DB
        pqxx::transaction<> txn(conn, "insert-HistoricalMin");
        for (auto& i: tohlcvs) {
            pqxx::result res = txn.prepared("insert-ESTOHLCV") \
            (exchid) \
            (symbid) \
            //(ceil<seconds>(i.time).time_since_epoch().count())
            (format("%F %T%z", i.time))
            (i.open) \
            (i.high) \
            (i.low) \
            (i.close) \
            (i.volume) \
            .exec();
            
            //std::cout << exch << '|' << fsym << tsym << '|' << make_zoned(current_zone(), floor<minutes>(i.time)) \
            << '|' << i.open << '|' << i.close << '|' << i.volume << '|' << std::endl;
        }
        txn.commit();
        std::cout << tohlcvs.size() << " TOHLCVs are inserted in DB\n";
}
```
In any case thanks in advance for an advice.

**Comment by jtv** [comment] 2019-02-19 22:47
Try `pqxx::stream_to`.

**Comment by MaximNM** [comment] 2019-02-20 10:48
Ok thanks. But why is so slowly by inserts in one transaction?
I really don't understand.

**Comment by tt4g** [comment] 2019-02-20 11:41
@MaximNM 
First of all I think you need to investigate which of C ++ and PostgreSQL are slow.

PostgreSQL may be delayed by execution of query plan and triggers.
Since there are 1.5M rows inserted, data transfer speed and memory may be a problem.

These should be investigated from the situation of slow query logs and network traffic.

For C ++ it's better to use faster functions.
 `pqxx::row::operator[](size_type)` is better than `pqxx::row::operator[](const std::string&)`

Also as says.

**Comment by tt4g** [comment] 2019-02-20 12:14
I noticed.

You are doing 1.5M rows `SELECT ... FROM historicalmin` and doing `INSERThistoricalmin_test ...` 1.5M times at the same time.

PostgreSQL repeatedly executes one insertion 1.5M times while sending 1.5M of data.

This is a very expensive process so you should manipulate the data little by little.

**Comment by KayEss** [comment] 2019-02-20 12:25
Just to add to tt4g's already good answer, what you find that kills you over the network compared to locally is the round trips. You have to send something to postgres for the INSERT and it must reply before you can start the next row insert.

Given your numbers you're seeing just under 1ms per row. This makes me think that your LAN is actually pretty fast, but will of course never be anywhere near as fast 

For HTTP I typically see a 10x drop in number of requests per seconds over 1Gbps LAN compared to local. You're getting less than that so it's actually pretty good.

**Comment by jtv** [comment] 2019-02-20 12:38
@MaximNM first thing to do if you want help is reduce the problem to a minimal example.  I don't have time to read and debug your full code!

My first guess at an answer is always: if you're doing INSERTs one row at a time, you're doing these steps over and over again:
1. Compose SQL to insert that row.
2. Send that SQL to the server, over the network.
3. Let the server insert the row.
4. Wait for the server to confirm, over the network.

To make things worse, if you do it in a `nontransaction`, _every SQL command is going to be its own little transaction._  So effectively, you get an implicit commit for every row.  You can probably get some speedup just by bundling a bunch of rows into a real transaction and committing them at once.  Or maybe you can even afford to insert all rows in a single transaction.  Of course it also depends on the transactional semantics you want.

If you use `stream_to` instead, all those inserts act as a single large transaction.  Moreover, it sends a whole bunch of rows over the network at the same time, and it doesn't sit still while waiting for a confirmation.  It's going to be much faster.

**Comment by MaximNM** [comment] 2019-02-20 13:05
@jtv Thanks and sorry to disturb you. Please see below I leaved only the inserting code as you can see I'm doing all inserting in one transaction.
```
std::string conn_string{"host= dbname= user= password="};
pqxx::connection conn(conn_string);
conn.prepare("insert-ESTOHLCV", "insert into historicalmin_test (id, exchangeid, symbolid, time, open, high, low, close, volume) values (0, $1, $2, $3, $4, $5, $6, $7, $8::float8::numeric::money)");
// Inserting
pqxx::transaction<> txn(conn, "insert-HistoricalMin");
for (auto& i: tohlcvs)
            pqxx::result res = txn.prepared("insert-ESTOHLCV") \
            (exchid) \
            (symbid) \
            //(ceil<seconds>(i.time).time_since_epoch().count())
            (format("%F %T%z", i.time))
            (i.open) \
            (i.high) \
            (i.low) \
            (i.close) \
            (i.volume) \
            .exec();
txn.commit();
```
I'm not able to use libpqxx 6.3 with stream_to as it's not in our production yet.
But I have tried tablewriter it really helps now it takes 18 seconds instead of 22 minutes over ethernet 1G and an hour over wifi.

@KayEss thanks for your comments it almost clear now.

**Comment by jtv** [comment] 2019-02-20 13:31
Yes, `tablewriter` is the direct predecessor to `stream_to`.  The idea is the same, the basic mechanism is the same.  The main reason why it needed replacement was encodings.  But if you're working in UTF-8 or a single-byte encoding, this should not be a problem.

**Comment by jtv** [comment] 2019-02-20 13:34
I'll put some better documentation in place so that other people won't need to run into the same questions.

**Comment by jtv** [comment] 2019-02-22 09:49
Documentation for `stream_to` has been fleshed out a little.  I'll try and remember to do the same for `stream_from` and general performance documentation.  The reason that `tablewriter` was not documented was that it sat there deprecated for a long time, and I didn't want to encourage new use of it.  Thankfully that has now been resolved thanks to `stream_to`.

Meanwhile I'll close this issue.  But feel free to open another one if you run into anything else.  I'm sorry if I was a little harsh initially; the tradition is to start by finding the simplest possible code to reproduce the problem, and I was a little stressed out with other things at that time.

**Closed by jtv** 2019-02-22 09:49 UTC

**Comment by MaximNM** [comment] 2019-02-24 19:39
@jtv Thanks for support!
