### ISSUE TITLE
Warning on Mac in ld while building with clang

### ISSUE THREAD

**Issue by skwllsp** [jtv/libpqxx#62] opened 2018-02-09 15:34 UTC
> ld: warning: direct access in function '`std::__1::__shared_ptr_pointer<pg_result const*, void (*)(pg_result const*), std::__1::allocator<pg_result const> >::__get_deleter(std::type_info const&) const' from file '/Users/sergey.kurenkov/src/tests/env/lib/libpqxx.a(connection_base.o)`' to global weak symbol 'typeinfo name for `void (*)(pg_result const*)`' from file 'CMakeFiles/tests.dir/__/__/tests/test.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

clang:

```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```

**Comment by KayEss** [comment] 2018-02-10 07:16
This looks likely to be caused by your build options. Where are you getting the cmake configuration from?

**Comment by jtv** [comment] 2018-02-12 10:00
(Inserted some backticks into your text to stop Github from interpreting bits of the error message as Wiki markup...)

**Comment by jtv** [comment] 2018-02-12 10:18
AFAICS the function in question is `clear_result`.  But that's not a weak symbol — it's declared in result.hxx and defined in result.cxx.  There could be a bug in the CMake setup, but perhaps also the `pg_result` declaration needs to be explicitly exported.

As an experiment, in include/pqxx/forward.hxx, could you replace the `struct pg_result;` with `struct PQXX_LIBEXPORT pg_result;` and see if that fixes the warning?

**Comment by skwllsp** [comment] 2018-02-19 08:24
I have created a test program that reproduce a linker warning on mac:

```
$ cat mytest/pqxx_test.cpp 
#include <pqxx/pqxx>

int main() {
	pqxx::result r;
}
```

I cloned the lipqxx repo and built it: 
` ./configure --prefix=$PWD/dist && make && make install
`

Then I compiled my test program:
```
$ clang++  --std=c++11 -I $PWD/dist/include -L $PWD/dist/lib mytest/pqxx_test.cpp -lpqxx -lpq 
ld: warning: direct access in function 'std::__1::__shared_ptr_pointer<pg_result const*, void (*)(pg_result const*), std::__1::allocator<pg_result const> >::__get_deleter(std::type_info const&) const' from file '/Users/sergey.kurenkov/src/test_libpqxx/dist/lib/libpqxx.a(result.o)' to global weak symbol 'typeinfo name for void (*)(pg_result const*)' from file '/var/folders/8k/wmd646w54nb94_rfs6l1rn312bkjmr/T/pqxx_test-a62599.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

In my opinion the warning is caused by using in result.hxx shared_ptr:
 using data_pointer = std::shared_ptr<const internal::pq::PGresult>;

**Comment by KayEss** [comment] 2018-02-22 05:09
You should use the same compile configuration for the configure script as you do for your build (although I believe Jeroen defaults to c++11, it'd still be important if you wanted 14 or even 17).

    ./configure CXXFLAGS=-std=c++11  --prefix=$PWD/dist

I have often noticed that older versions of clang have some bugs with regard to `shared_ptr` code generation, but this error doesn't look like one of them.

I've just switched my projects to the latest pqxx and need to fix up some headers, but I'll report back on whether or not I see any warnings when I get a working build again.

**Comment by KayEss** [comment] 2018-02-25 08:00
I've done some builds (C++14) with the latest code for libpqxx and don't get any warnings on the Mac. However, when I do what you've done I do get the warning. 

I'm not using the supplied make files though. I build the libpqxx sources using the same build that I then build the application with, and this ensures that the compile options are exactly alike. Can you try to include the libpqxx sources into your build rather than using make separately?

**Comment by skwllsp** [comment] 2018-02-26 12:12
>Can you try to include the libpqxx sources into your build rather than using make separately?
Look if I add `-fvisibility=hidden -fvisibility-inlines-hidden` to clang I get no warning:

```
$ clang++ -fvisibility=hidden -fvisibility-inlines-hidden -g  --std=c++11 -I $PWD/dist/include -L $PWD/dist/lib mytest/pqxx_test.cpp -o mytest/pqxx_test -lpqxx -lpq 
➜  18-02-26 15:07:10 /Users/sergey.kurenkov/src/test_libpqxx git:(master) ✗ 
```

**Comment by jtv** [comment] 2018-03-03 18:29
It doesn't help that I can't reproduce this on an Ubuntu system.  :(  @skwllsp, have you tried adding `PQXX_LIBEXPORT` to that `using` declaration, to see whether that would convince the compiler to keep the type completely visible for linking?

**Comment by jtv** [comment] 2018-04-26 17:56
Annoying situation: we can't reproduce it, and a warning isn't _quite_ serious enough to warrant a lot of effort.  I don't think we're going to get around to it, so I'll just close the issue.

If it comes up again, we can take that as a sign that it deserves more attention.

**Closed by jtv** 2018-04-26 17:56 UTC
